<div style="background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%); padding: 50px 40px; border-radius: 16px; text-align: center; font-family: 'Segoe UI', Arial, sans-serif; border: 1px solid #e94560;">

<h1 style="color: #e94560; font-size: 2.6em; margin: 0 0 8px 0; letter-spacing: 1px;">🐼 Pandas Practice Series</h1>
<h2 style="color: #a8dadc; font-size: 1.5em; margin: 0 0 6px 0; font-weight: 400;">Notebook 1 of 5</h2>
<h3 style="color: #f1faee; font-size: 1.1em; margin: 0 0 24px 0; font-weight: 300; letter-spacing: 2px;">REAL-WORLD PRODUCTION DATA · 50 INTERVIEW QUESTIONS</h3>
<hr style="border: 1px solid #e94560; width: 60%; margin: 20px auto;"/>
<p style="color: #a8dadc; font-size: 1.0em; margin: 0;">📊 Datasets: Employees · Departments · Orders · Customers · Products · Vendors · Attendance · Transactions</p>
<p style="color: #f1faee; font-size: 0.9em; margin: 8px 0 0 0;">🎯 Target: Data Science · AI/ML · Software Engineering Freshers &amp; Beginners</p>

</div>

---

## 📋 Overview

Welcome to **Notebook 1** of the **Pandas Practice Series** — a premium, interview-focused practice resource designed for freshers and early-career professionals preparing for **Data Science, AI/ML, and Software Engineering** interviews.

This notebook uses **8 realistic, production-like CSV datasets** that intentionally include the kinds of data quality issues you will encounter in real jobs:

| Dataset | File | Description |
|---|---|---|
| 👤 Employees | `employees.csv` | ~118 rows · salary, hire dates, status, city |
| 🏢 Departments | `departments.csv` | 8 rows · budgets, managers, locations |
| 🛒 Orders | `orders.csv` | 200 rows · order status, payment, amounts |
| 👥 Customers | `customers.csv` | 65 rows · segments, purchases, join dates |
| 📦 Products | `products.csv` | 30 rows · categories, prices, stock |
| 🚚 Vendors | `vendors.csv` | 8 rows · contracts, ratings, spend |
| 📅 Attendance | `attendance.csv` | 300 rows · monthly attendance, overtime |
| 💳 Transactions | `transactions.csv` | 250 rows · financial transactions |

### ⚠️ Production Data Issues (Intentionally Included)

| Issue Type | Example |
|---|---|
| Missing values | Salaries, amounts, ratings |
| Duplicate rows / IDs | Same employee or order appears twice |
| Mixed capitalization | `"RAVI VERMA"`, `"ravi verma"`, `"Ravi Verma"` |
| Leading / trailing spaces | `"  deepak joshi  "` |
| Inconsistent category names | `"Electronics"` vs `"electronics"` |
| Cancelled / returned orders | Realistic business statuses |
| Pending payments | Realistic financial statuses |

---

## 🎯 Learning Objectives

By the end of this notebook, you will be able to:

1. **Load and inspect** real-world data using Pandas
2. **Identify and handle** missing values, duplicates, and dirty data
3. **Filter, sort, and select** data using multi-condition logic
4. **Group and aggregate** data to extract business insights
5. **Merge** multiple datasets to answer cross-table questions
6. **Rank** records within groups using Pandas ranking
7. **Transform** data with `groupby` + `transform` patterns
8. **Clean strings** using vectorized string methods
9. **Work with datetime** columns for time-based analysis
10. **Build pivot tables** for multi-dimensional aggregation

---

## 📈 Difficulty Roadmap

```
Questions  1 –  5  │  🟢  Easy
Questions  6 – 15  │  🟡  Easy-Medium
Questions 16 – 25  │  🟠  Medium
Questions 26 – 38  │  🔴  Medium-Hard
Questions 39 – 50  │  🔥  Hard
```

> **Current batch:** Questions 1–10 (🟢 Easy → 🟡 Easy-Medium)

---

## 📜 Rules and Instructions

| Rule | Details |
|---|---|
| ✅ **Library** | Use **only** `import pandas as pd`. No NumPy, no Seaborn, no other libraries. |
| ✅ **Vectorized only** | Solve everything with vectorized Pandas. No `for`, `while`, `iterrows()`, `apply()`, list comprehensions. |
| ✅ **Multi-concept** | Every question combines 2 or more Pandas concepts. Think before you code. |
| ✅ **Hints available** | Each question has a hidden hint cell — expand it only when you are truly stuck. |
| ✅ **No solution provided** | Solutions are intentionally omitted. Think, experiment, and learn. |
| ✅ **Code cells are blank** | Your working space is completely empty — fill it in. |

---

## 🚀 Setup — Run This First

In [29]:
import pandas as pd

# Load all datasets
employees  = pd.read_csv("Data/employees.csv")
departments = pd.read_csv("Data/departments.csv")
orders      = pd.read_csv("Data/orders.csv")
customers   = pd.read_csv("Data/customers.csv")
vendors     = pd.read_csv("Data/vendors.csv")
products    = pd.read_csv("Data/products.csv")
attendance  = pd.read_csv("Data/attendance.csv")
transactions = pd.read_csv("Data/transactions.csv")

print('All datasets loaded successfully!')
print(f'   employees    : {employees.shape}')
print(f'   departments  : {departments.shape}')
print(f'   orders       : {orders.shape}')
print(f'   customers    : {customers.shape}')
print(f'   products     : {products.shape}')
print(f'   vendors      : {vendors.shape}')
print(f'   attendance   : {attendance.shape}')
print(f'   transactions : {transactions.shape}')

All datasets loaded successfully!
   employees    : (120, 8)
   departments  : (8, 5)
   orders       : (200, 9)
   customers    : (60, 7)
   products     : (30, 7)
   vendors      : (8, 8)
   attendance   : (300, 6)
   transactions : (250, 8)

---
---

# 🟢 Section 1 — Easy (Questions 1–5)

---

## ❓ Question 1

---

| | |
|---|---|
| **Question #** | 1 of 50 |
| **Difficulty** | 🟢 Easy |
| **Interview Level** | Fresher / Entry-Level |

### 🏢 Business Scenario

The HR team needs an **Active Employee Directory** to share with all department managers. They want a clean, focused view — only active employees, only the columns that matter, sorted by salary so high-earners appear first.

### 📝 Problem Statement

From the `employees` dataset, filter only **Active** employees, select the columns `emp_id`, `employee_name`, `dept_id`, `salary_inr`, and `city`, then sort the result by `salary_inr` in **descending** order.

### ✅ Requirements

1. Filter rows where `status == 'Active'`
2. Select only the 5 specified columns (in that order)
3. Sort by `salary_inr` descending
4. Reset the index

### 📊 Expected Output Format

| index | emp_id | employee_name | dept_id | salary_inr | city |
|---|---|---|---|---|---|
| 0 | E... | ... | D... | 114000.0 | ... |
| 1 | E... | ... | D... | 112000.0 | ... |
| ... | | | | | |

> Note: Some salary values may be NaN — they should still appear in the result (at the bottom after sorting).

### 🧠 Concepts Tested

```
Boolean Filtering  +  Column Selection  +  Sorting  +  Index Reset
```

In [9]:
active_emp = (
    employees[employees['status'] == 'Active']
    .sort_values(
        by='salary_inr',
        ascending=False,
        ignore_index=True,
        na_position='last'
    )[['emp_id', 'employee_name', 'dept_id', 'salary_inr', 'city']]
)

active_emp

    emp_id   employee_name dept_id  salary_inr       city
0     E092    Pramod Yadav     D07    114000.0     Mumbai
1     E072    Varun Bansal     D03    112000.0    Chennai
2     E052  Meenal Chauhan     D07    110000.0  Hyderabad
3     E032    Ashwin Reddy     D03    108000.0     Mumbai
4     E081   Ramesh Sheikh     D04    105000.0      Delhi
..     ...             ...     ...         ...        ...
98    E091    Nalini Bhatt     D06         NaN  Bengaluru
99    E097    Prachi Verma     D04         NaN  Bengaluru
100   E017  Kavya Krishnan     D04         NaN       Pune
101   E103    Simran Batra     NaN         NaN      Delhi
102   E116   KOMAL BHOSALE     D08         NaN  Hyderabad

[103 rows x 5 columns]

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Use a **boolean mask** on the `status` column to filter Active employees.
- Column selection can be done by passing a **list of column names** inside double brackets.
- Think about the **order** of operations: filter first, then select, then sort.
- `NaN` values in numeric columns are placed **last** by default when sorting — you may want to verify this behavior.
- Consider whether you need to sort **in place** or return a new DataFrame.

</details>

---
---


## ❓ Question 2

---

| | |
|---|---|
| **Question #** | 2 of 50 |
| **Difficulty** | 🟢 Easy |
| **Interview Level** | Fresher / Entry-Level |

### 🏢 Business Scenario

Before any analysis, the Data Engineering team performs a **data quality audit**. They need a summary report showing, for each column in the `employees` dataset, exactly how many values are missing and what percentage of the total rows that represents — sorted from the most missing to the least.

### 📝 Problem Statement

Using the `employees` DataFrame, produce a **missing value audit report** showing:

- `missing_count` — number of missing values in each column
- `missing_pct` — percentage of missing values, **rounded to 2 decimal places**

Include **only columns that have at least 1 missing value**. Sort the result by `missing_pct` in **descending** order.

### ✅ Requirements

1. Compute missing count per column
2. Compute missing percentage per column (relative to total rows)
3. Round percentage to 2 decimal places
4. Filter out columns with zero missing values
5. Sort by percentage descending

### 📊 Expected Output Format

| column | missing_count | missing_pct |
|---|---|---|
| salary_inr | ... | ...% |
| dept_id | ... | ...% |
| ... | ... | ... |

### 🧠 Concepts Tested

```
isnull() + sum() + Arithmetic on Series + round() + Boolean Filtering + sort_values()
```

In [21]:
missing_count = employees.isna().sum().to_frame(name='missing_count')
missing_pct = (employees.isna().mean() * 100).round(2).to_frame('missing_pct')

missing_report = (
    missing_count
    .join(missing_pct)
    .sort_values(by='missing_count', 
                 ascending=False)
)

missing_report

               missing_count  missing_pct
salary_inr                19        15.83
dept_id                    2         1.67
employee_name              0         0.00
emp_id                     0         0.00
hire_date                  0         0.00
city                       0         0.00
status                     0         0.00
gender                     0         0.00

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `isnull().sum()` gives you the missing count per column as a **Series**.
- You can build a DataFrame directly from multiple Series using `pd.DataFrame()`.
- To get the percentage, divide `missing_count` by `len(df)` and multiply by 100.
- Think about how to **filter** the resulting DataFrame to keep only rows where `missing_count > 0`.
- Do not forget to sort **after** filtering.

</details>

---

## ❓ Question 3

---

| | |
|---|---|
| **Question #** | 3 of 50 |
| **Difficulty** | 🟢 Easy |
| **Interview Level** | Fresher / Entry-Level |

### 🏢 Business Scenario

The `customers` dataset was collected from multiple intake forms where names were entered by hand. The result is inconsistent casing and extra whitespace. Before any customer analysis, the **Marketing team** wants the dataset cleaned and then wants to know **how many unique customers exist per city**, sorted by count from highest to lowest.

### 📝 Problem Statement

In the `customers` DataFrame:

1. **Clean** the `customer_name` column: strip leading/trailing spaces and convert to **Title Case**
2. **Drop exact duplicate rows** (same `customer_id` appearing more than once)
3. Count the number of **unique customers per city** (using the deduplicated data)
4. Return the result as a Series or DataFrame, sorted by count **descending**

### ✅ Requirements

1. Use `.str.strip()` and `.str.title()` for cleaning
2. Drop duplicates based on `customer_id`
3. Use `value_counts()` on the `city` column
4. Result must be sorted highest count first

### 📊 Expected Output Format

| city | count |
|---|---|
| Delhi | ... |
| Mumbai | ... |
| ... | ... |

### 🧠 Concepts Tested

```
String Cleaning (.str.strip, .str.title)  +  Drop Duplicates  +  value_counts()
```

In [30]:
customers['customer_name'] = customers['customer_name'].str.strip().str.title()
customers['city'] = customers['city'].str.strip().str.title()

customers.drop_duplicates(subset=['customer_id'],
                          inplace=True)

unique_customers = customers['city'].value_counts().to_frame().reset_index()
unique_customers

        city  count
0  Bengaluru     10
1     Mumbai      9
2      Delhi      9
3  Hyderabad      9
4       Pune      9
5    Chennai      9

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- String operations on a column use the `.str` accessor — you can **chain** `.str.strip()` and `.str.title()` together.
- `drop_duplicates(subset=...)` lets you specify which columns to consider when identifying duplicates.
- `value_counts()` already returns results sorted by frequency — check whether you need to sort again.
- Think about whether the cleaning should happen **before or after** deduplication, and why.

</details>

---

## ❓ Question 4

---

| | |
|---|---|
| **Question #** | 4 of 50 |
| **Difficulty** | 🟢 Easy |
| **Interview Level** | Fresher / Entry-Level |

### 🏢 Business Scenario

The Finance team is auditing **high-value orders**. They want to see only the orders that were:
- Successfully **Delivered**
- Paid via **Credit Card** or **UPI**
- With an order amount greater than **₹50,000**

Results should be sorted by `amount_inr` descending, and only specific columns should be shown.

### 📝 Problem Statement

From the `orders` DataFrame, apply all three filters simultaneously and return only the columns:
`order_id`, `customer_id`, `product_id`, `order_date`, `amount_inr`, `payment_method`

Sort by `amount_inr` descending. Reset the index.

### ✅ Requirements

1. Filter: `order_status == 'Delivered'`
2. Filter: `payment_method` is `'Credit Card'` OR `'UPI'`
3. Filter: `amount_inr > 50000`
4. Select only the 6 specified columns
5. Sort by `amount_inr` descending, reset index

### 📊 Expected Output Format

| index | order_id | customer_id | product_id | order_date | amount_inr | payment_method |
|---|---|---|---|---|---|---|
| 0 | O... | C... | P... | 20xx-xx-xx | 899990.0 | Credit Card |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Multi-condition Filtering  +  isin()  +  Column Selection  +  Sorting  +  Index Reset
```

In [35]:
high_value_orders = orders[
    (orders['order_status'] == 'Delivered') & 
    (orders['payment_method'].isin(['Credit Card','UPI'])) &
    (orders['amount_inr'] > 50_000)
].sort_values(by='amount_inr',
              ascending=False,
              ignore_index=True)[['order_id','customer_id','product_id','order_date','amount_inr','payment_method']]

high_value_orders

  order_id customer_id product_id  order_date  amount_inr payment_method
0    O0164        C051       P025  2022-10-23    449995.0            UPI
1    O0016        C028       P017  2022-09-12    249990.0    Credit Card
2    O0182        C049       P026  2022-01-02    206991.0    Credit Card
3    O0151        C026       P015  2023-04-27    199995.0            UPI
4    O0052        C007       P028  2023-07-20    143991.0    Credit Card
5    O0156        C032       P004  2023-11-18     90993.0            UPI
6    O0136        C026       P004  2024-02-21     79998.0            UPI
7    O0010        C007       P012  2022-06-05     74997.0            UPI
8    O0055        C023       P007  2022-01-03     53994.0            UPI
9    O0051        C025       P017  2022-06-27     51996.0            UPI

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- When combining multiple conditions, wrap each condition in parentheses and use `&` (AND) and `|` (OR) — **not** Python's `and`/`or`.
- For checking membership in a list of values, `.isin([...])` is cleaner than chaining `|` conditions.
- Missing `amount_inr` values will **automatically be excluded** by the `> 50000` filter — think about why.
- The order of operations matters: filter all conditions first, then select columns, then sort.

</details>

---

## ❓ Question 5

---

| | |
|---|---|
| **Question #** | 5 of 50 |
| **Difficulty** | 🟢 Easy |
| **Interview Level** | Fresher / Entry-Level |

### 🏢 Business Scenario

The HR Head wants a **department-level salary report** to understand how salaries are distributed across departments. The report should show, per department: the **average salary**, the **highest salary**, the **lowest salary**, and the **total headcount** — for **Active employees only**, sorted by average salary descending.

### 📝 Problem Statement

From the `employees` DataFrame:

1. Filter to **Active** employees only
2. Group by `dept_id`
3. Aggregate `salary_inr` to compute:
   - `avg_salary` — mean, rounded to 0 decimal places
   - `max_salary` — maximum
   - `min_salary` — minimum
   - `headcount` — count of employees (use `count` on salary; missing salaries excluded from count)
4. Sort by `avg_salary` descending
5. Reset index

### ✅ Requirements

- Use named aggregation (`.agg()` with keyword arguments)
- Missing `salary_inr` values should not be included in count
- Round `avg_salary` to 0 decimal places after aggregation

### 📊 Expected Output Format

| dept_id | avg_salary | max_salary | min_salary | headcount |
|---|---|---|---|---|
| D07 | 108000.0 | 114000.0 | ... | ... |
| D05 | ... | ... | ... | ... |
| ... | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  GroupBy  +  Named Aggregation  +  round()  +  sort_values()  +  reset_index()
```

In [46]:
employees[employees['status'] == 'Active'] \
    .groupby('dept_id') \
    .agg(
        avg_salary=('salary_inr', 'mean'),
        highest_salary=('salary_inr', 'max'),
        lowest_salary=('salary_inr', 'min'),
        headcount=('emp_id', 'count')
    ) \
    .round({'avg_salary': 2}) \
    .sort_values(by='avg_salary', ascending=False)

         avg_salary  highest_salary  lowest_salary  headcount
dept_id
D07        90500.00        114000.0        62000.0         10
D04        90000.00        105000.0        74000.0         13
D03        87500.00        112000.0        64000.0         14
D08        87111.11        103000.0        72000.0         12
D01        81846.15         96000.0        58000.0         13
D05        79538.46         98000.0        55000.0         14
D06        77714.29         97000.0        64000.0         11
D02        75545.45         95000.0        64000.0         14

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Filter **before** grouping — it is both semantically correct and more efficient.
- Named aggregation syntax: `.agg(new_col_name=('column', 'function'))`
- `mean()` by default **skips NaN values** — so your average will be computed only over employees who have a salary recorded.
- `count()` also skips NaN — which is exactly what you want for headcount of employees with known salaries.
- Apply `round()` **after** the aggregation, not inside it.

</details>

---
---

# 🟡 Section 2 — Easy-Medium (Questions 6–10)

---

## ❓ Question 6

---

| | |
|---|---|
| **Question #** | 6 of 50 |
| **Difficulty** | 🟡 Easy-Medium |
| **Interview Level** | Fresher-to-Junior |

### 🏢 Business Scenario

Management wants a **full employee roster** enriched with department names and manager information. However, some employees in the system are assigned to department IDs that **do not exist** in the departments master table. The team wants these employees **excluded** from the final roster, and the result should show only essential columns, sorted by department name and then by employee name.

### 📝 Problem Statement

Merge `employees` with `departments` on `dept_id`. Keep only employees whose department **exists** in the departments table (inner join). From the merged result, select:

`emp_id`, `employee_name`, `department_name`, `manager_name`, `salary_inr`, `city`

Sort by `department_name` ascending, then `employee_name` ascending. Reset index.

### ✅ Requirements

1. Merge on `dept_id` using an **inner join**
2. Select only the 6 specified columns
3. Sort by `department_name` ASC, then `employee_name` ASC
4. Reset index

> **Note:** The `departments.csv` has a duplicate department entry with inconsistent casing (`"engineering"` vs `"Engineering"`). The join will handle this automatically — observe how many rows you get.

### 📊 Expected Output Format

| index | emp_id | employee_name | department_name | manager_name | salary_inr | city |
|---|---|---|---|---|---|---|
| 0 | E... | ... | Data Science | ... | ... | ... |
| 1 | E... | ... | Engineering | ... | ... | ... |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Merge (Inner Join)  +  Column Selection  +  Multi-column Sorting  +  Index Reset
```

In [56]:
final_roster = pd.merge(
    employees,departments,
    on='dept_id',
    how='inner')\
    [['emp_id', 'department_name', 'employee_name', 'manager_name', 'salary_inr', 'city']]\
    .sort_values(by=['department_name', 'employee_name'],
    ignore_index=True

)

final_roster

    emp_id department_name  employee_name  manager_name  salary_inr       city
0     E029    Data Science     Asha Menon           NaN     93000.0       Pune
1     E077    Data Science  Chitra Sharma           NaN         NaN       Pune
2     E108    Data Science  Devyani Patil           NaN     91000.0     Mumbai
3     E093    Data Science     Geeta Jain           NaN     80000.0      Delhi
4     E116    Data Science  KOMAL BHOSALE           NaN         NaN  Hyderabad
..     ...             ...            ...           ...         ...        ...
113   E115     engineering   Sandip Pawar  Rajesh Kumar     87000.0      Delhi
114   E068     engineering   Sriram Reddy  Rajesh Kumar     83000.0     Mumbai
115   E036     engineering   Suraj Bansal  Rajesh Kumar     85000.0    Chennai
116   E107     engineering    Tanmay More  Rajesh Kumar     76000.0  Bengaluru
117   E084     engineering    Usha Tiwari  Rajesh Kumar     98000.0    Chennai

[118 rows x 6 columns]

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `pd.merge(left, right, on='key', how='inner')` keeps only rows where the key exists in **both** DataFrames.
- After merging, both DataFrames' columns appear — you will need to select only the ones required.
- For multi-column sorting, pass a **list** to `by=` and a **list** to `ascending=`.
- Notice: some employees have `dept_id` values that do not exist in `departments.csv` — an inner join will naturally drop them.
- The `departments.csv` has `'engineering'` (lowercase) as a duplicate entry — inner join will match it with employees assigned D07, so you may see more rows than expected.

</details>

---

## ❓ Question 7

---

| | |
|---|---|
| **Question #** | 7 of 50 |
| **Difficulty** | 🟡 Easy-Medium |
| **Interview Level** | Fresher-to-Junior |

### 🏢 Business Scenario

The HR team wants to identify **above-average earners within each department**. Rather than computing each department's average manually, they want a single Pandas operation that adds the department average as a new column, and then filters to employees who earn **more than their own department's average salary**.

### 📝 Problem Statement

From the `employees` DataFrame:

1. Consider only **Active** employees with a **non-null salary**
2. Add a new column `dept_avg_salary` containing the **mean salary of the employee's department** (using `groupby` + `transform`)
3. Filter to keep only employees whose `salary_inr` is **strictly greater than** their `dept_avg_salary`
4. Select: `emp_id`, `employee_name`, `dept_id`, `salary_inr`, `dept_avg_salary`
5. Round `dept_avg_salary` to 2 decimal places
6. Sort by `dept_id` ASC, then `salary_inr` DESC
7. Reset index

### ✅ Requirements

- Use `groupby().transform('mean')` — **not** `groupby().agg()`
- The `transform` should broadcast the department average back to every row
- No loops, no apply

### 📊 Expected Output Format

| index | emp_id | employee_name | dept_id | salary_inr | dept_avg_salary |
|---|---|---|---|---|---|
| 0 | E... | ... | D01 | 105000.0 | 89xxx.xx |
| 1 | E... | ... | D01 | 101000.0 | 89xxx.xx |
| ... | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  GroupBy + Transform  +  Comparison Filtering  +  Column Selection  +  Sorting
```

In [24]:
result = employees[(employees['status'] == 'Active') & (employees['salary_inr'].notna())].copy()

result['dept_avg_salary'] = result.groupby('dept_id')['salary_inr'].transform('mean').round(2)

result = result[
    result["salary_inr"] > result["dept_avg_salary"]
][["emp_id", "employee_name", "dept_id", "salary_inr", "dept_avg_salary"]].sort_values(by=['dept_id','salary_inr'],
                                                                                       ascending=[True,False],
                                                                                       ignore_index=True)

display(result.head())

  emp_id   employee_name dept_id  salary_inr  dept_avg_salary
0   E054   Sanjay Bansal     D01     96000.0         81846.15
1   E006    Anjali Singh     D01     95000.0         81846.15
2   E117  Tushar Gaikwad     D01     95000.0         81846.15
3   E086    Neeraj Reddy     D01     93000.0         81846.15
4   E046    Sachin Kumar     D01     89000.0         81846.15

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `groupby().transform('mean')` returns a Series of the **same length** as the original DataFrame — each value is the mean of its group. This is what makes it different from `agg()`.
- Filter for Active + non-null salary **before** computing the transform — this ensures the department average is computed correctly.
- Assign the result of `transform` as a new column on the filtered DataFrame.
- Then use a simple boolean comparison `salary_inr > dept_avg_salary` to filter.
- Missing salaries may propagate into `transform` — filtering them out first avoids this.

</details>

---

## ❓ Question 8

---

| | |
|---|---|
| **Question #** | 8 of 50 |
| **Difficulty** | 🟡 Easy-Medium |
| **Interview Level** | Fresher-to-Junior |

### 🏢 Business Scenario

The Finance team needs a **year-wise order revenue summary** to understand business growth. They want to see total revenue from **Delivered** orders only, grouped by the year the order was placed — sorted chronologically. Only years with **more than 20** delivered orders should be included.

### 📝 Problem Statement

From the `orders` DataFrame:

1. Parse `order_date` as a datetime column
2. Extract the **year** from `order_date` into a new column `order_year`
3. Filter to orders where `order_status == 'Delivered'` **and** `amount_inr` is **not null**
4. Group by `order_year` and compute:
   - `total_orders` — count of orders
   - `total_revenue` — sum of `amount_inr`, rounded to 2 decimal places
   - `avg_order_value` — mean of `amount_inr`, rounded to 2 decimal places
5. Filter to include only years where `total_orders > 20`
6. Sort by `order_year` ascending
7. Reset index

### ✅ Requirements

- Use `pd.to_datetime()` for parsing
- Use `.dt.year` to extract the year
- Use named aggregation inside `.agg()`
- Filter the grouped result (not the raw data) for `total_orders > 20`

### 📊 Expected Output Format

| order_year | total_orders | total_revenue | avg_order_value |
|---|---|---|---|
| 2022 | ... | ... | ... |
| 2023 | ... | ... | ... |
| 2024 | ... | ... | ... |

### 🧠 Concepts Tested

```
Datetime Parsing  +  .dt accessor  +  Boolean Filtering  +  GroupBy  +  Named Aggregation  +  Post-Aggregation Filtering
```

In [43]:
result = orders[orders["order_status"] == "Delivered"].copy()

result["order_year"] = result["order_date"].dt.year

result = (
    result.groupby("order_year")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("amount_inr", "sum"),
        avg_order_value=("amount_inr", "mean")
    )
    .query("total_orders > 20")
    .sort_index()
    .reset_index()
    .round({"avg_order_value" : 2})
)

display(result)

   order_year  total_orders  total_revenue  avg_order_value
0        2022            32      1884830.0         64994.14
1        2023            31      1255683.0         48295.50

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Use `pd.to_datetime(df['col'])` to convert a string column to datetime. You can assign it back to the same column.
- After conversion, `.dt.year` extracts the integer year from each date.
- Filter for Delivered orders **and** non-null amounts before grouping — this keeps your revenue calculations clean.
- The filter `total_orders > 20` is applied **after** aggregation — on the resulting grouped DataFrame.
- Think about whether you need to sort before or after the final filter.

</details>

---

## ❓ Question 9

---

| | |
|---|---|
| **Question #** | 9 of 50 |
| **Difficulty** | 🟡 Easy-Medium |
| **Interview Level** | Fresher-to-Junior |

### 🏢 Business Scenario

The Sales Analytics team wants a **customer segment performance dashboard**. They need to understand which customer segments (Enterprise, SMB, Retail) are generating the most revenue from **completed (Delivered)** orders. Before joining, the `customers.segment` column has **inconsistent casing** that must be standardized.

### 📝 Problem Statement

1. **Clean** the `segment` column in `customers`: standardize to **Title Case** (so `'enterprise'`, `'ENTERPRISE'` all become `'Enterprise'`)
2. **Drop duplicate** customer records (keep first occurrence per `customer_id`)
3. **Merge** `orders` (filter: `order_status == 'Delivered'` and `amount_inr` not null) with the cleaned `customers` on `customer_id` using a **left join from orders**
4. **Group** by `segment` and compute:
   - `total_orders` — count of orders
   - `total_revenue` — sum of `amount_inr`
   - `avg_order_value` — mean of `amount_inr`, rounded to 2 decimal places
   - `unique_customers` — number of distinct `customer_id` values
5. Filter out rows where `segment` is **null** (customers not found in the customers table)
6. Sort by `total_revenue` descending
7. Reset index

### ✅ Requirements

- Standardize segment using `.str.title()`
- Deduplicate customers before merging
- Use `nunique()` for unique customer count

### 📊 Expected Output Format

| segment | total_orders | total_revenue | avg_order_value | unique_customers |
|---|---|---|---|---|
| Enterprise | ... | ... | ... | ... |
| SMB | ... | ... | ... | ... |
| Retail | ... | ... | ... | ... |

### 🧠 Concepts Tested

```
String Cleaning  +  Drop Duplicates  +  Merge  +  GroupBy  +  Multiple Aggregations (sum, mean, count, nunique)  +  Filtering  +  Sorting
```

In [57]:
result = customers.copy()

# Step 1: Standardize segment names
result["segment"] = result["segment"].str.title()

# Step 2: Remove duplicate customers
result = result.drop_duplicates(subset="customer_id", 
                                keep="first")

# Step 3: Filter delivered orders with non-null amount
result = (
    orders[
        (orders["order_status"] == "Delivered") &
        (orders["amount_inr"].notna())
    ]
    .merge(result,
        on="customer_id",
        how="left"
    )
)

# Step 4 & 5: Remove customers not found in customers table
result = result[result["segment"].notna()]

# Step 6: Group and aggregate
result = (
    result.groupby("segment")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("amount_inr", "sum"),
        avg_order_value=("amount_inr", "mean"),
        unique_customers=("customer_id", "nunique")
    )
    .round({"avg_order_value" : 2, "total_revenue" : 2})
    .reset_index()
)


# Step 7: Sort and reset index
result = (
    result.sort_values(by="total_revenue", 
                       ascending=False,
                       ignore_index=True)
)

display(result)

      segment  total_orders  total_revenue  avg_order_value  unique_customers
0  Enterprise            23      1824064.0         79307.13                15
1         Smb            32      1064152.0         33254.75                16
2      Retail            17       587901.0         34582.41                11

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Clean the segment column **before** deduplication and **before** the merge.
- `drop_duplicates(subset='customer_id', keep='first')` keeps the first occurrence of each customer.
- For the merge: the **left** DataFrame should be the filtered orders, and the **right** should be the cleaned customers. Use `how='left'` so all orders are retained.
- After merging, some orders may not have a matching customer — their `segment` will be `NaN`. You need to filter these out.
- For multiple aggregation functions on the same column, use a dictionary inside `.agg()` or named aggregation.
- `nunique()` counts distinct values — use it for `unique_customers`.

</details>

---

## ❓ Question 10

---

| | |
|---|---|
| **Question #** | 10 of 50 |
| **Difficulty** | 🟡 Easy-Medium |
| **Interview Level** | Fresher-to-Junior |

### 🏢 Business Scenario

The HR Head wants to know the **Top 3 highest-paid Active employees in each department**, along with the actual department name (not just the ID). Employees without a known salary should be excluded. Ties in salary within a department should be handled using **dense ranking** (so no rank is skipped).

### 📝 Problem Statement

1. Merge `employees` (Active + non-null salary) with `departments` on `dept_id` using an **inner join**
2. Rank employees within each `department_name` by `salary_inr` in **descending** order using **dense ranking**
   - Add the rank as a new column `salary_rank`
3. Filter to keep only employees with `salary_rank <= 3`
4. Select: `department_name`, `emp_id`, `employee_name`, `salary_inr`, `salary_rank`
5. Sort by `department_name` ASC, `salary_rank` ASC
6. Reset index

### ✅ Requirements

- Use `groupby().rank(method='dense', ascending=False)` for ranking
- Convert rank to integer (`.astype(int)`) after filtering
- No `apply()`, no loops

### 📊 Expected Output Format

| index | department_name | emp_id | employee_name | salary_inr | salary_rank |
|---|---|---|---|---|---|
| 0 | Data Science | E... | ... | 114000.0 | 1 |
| 1 | Data Science | E... | ... | 110000.0 | 2 |
| 2 | Data Science | E... | ... | 108000.0 | 3 |
| 3 | Engineering | E... | ... | ... | 1 |
| ... | | | | | |

> Note: If two employees share the same salary within a department, they receive the **same rank** (dense), and both appear in the Top 3.

### 🧠 Concepts Tested

```
Merge (Inner Join)  +  GroupBy + Rank (Dense)  +  Boolean Filtering  +  Column Selection  +  Type Casting  +  Multi-column Sorting
```

In [80]:
# Step1: Make Copy

result = employees.copy()
dept = departments.copy()

# Step2: Clean Employees DF and Departments DF

result = result[
    (result['status'] == 'Active') & 
    (result['salary_inr'].notna())
]

dept['department_name'] = dept['department_name'].str.title()

# Step3: Merge Employees with Department ON dept_id

result = pd.merge(
        result,dept[['dept_id','department_name']],
         on='dept_id',
         how='inner'
)

# Step4: Rank employees within each department based on salary (highest salary = Rank 1)

result['salary_rank'] =  result.groupby('department_name')['salary_inr']\
                                .rank(method="dense", ascending=False).astype(int)

# Step5: Filtering top 3 ranks only

result = result[result['salary_rank'] <=3]

# Step6: Required Columns Sorting

result = result[['department_name','emp_id','employee_name','salary_inr','salary_rank']]

# Step7: 

result = result.sort_values(by=['department_name','salary_rank'],
                   ascending=[True,True])\
                .reset_index(drop=True)
display(result)

    department_name emp_id    employee_name  salary_inr  salary_rank
0      Data Science   E061      Sudha Verma    103000.0            1
1      Data Science   E021       Sneha Jain     98000.0            2
2      Data Science   E069      Madhuri Das     97000.0            3
3       Engineering   E092     Pramod Yadav    114000.0            1
4       Engineering   E052   Meenal Chauhan    110000.0            2
5       Engineering   E012    Nikhil Tiwari    105000.0            3
6           Finance   E074     Rakesh Yadav     98000.0            1
7           Finance   E034   Pranav Chauhan     94000.0            2
8           Finance   E113      Arun Sawant     93000.0            3
9   Human Resources   E081    Ramesh Sheikh    105000.0            1
10  Human Resources   E041      Renu Sharma    101000.0            2
11  Human Resources   E089  Indira Krishnan     99000.0            3
12        Marketing   E079       Alok Verma     95000.0            1
13        Marketing   E039      Shilpa Jain     91000.0            2
14        Marketing   E102    Yash Malhotra     88000.0            3
15       Operations   E099      Ritu Sheikh     97000.0            1
16       Operations   E059     Swati Sharma     93000.0            2
17       Operations   E106      Roshan Naik     82000.0            3
18            Sales   E072     Varun Bansal    112000.0            1
19            Sales   E032     Ashwin Reddy    108000.0            2
20            Sales   E064    Amitabh Kumar     96000.0            3

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Filter for Active employees with non-null salary **before** merging — keeps the operation clean.
- `groupby('department_name')['salary_inr'].rank(method='dense', ascending=False)` returns a float Series — you will need to convert to int **after** filtering.
- Assign the rank as a new column **before** filtering by rank.
- Dense ranking: if two employees share rank 1, the next employee gets rank 2 (not rank 3). This is different from `method='min'`.
- The inner join ensures only employees with valid department IDs are included — employees with missing or non-existent dept_id are excluded automatically.

</details>

---
---

# 🟠 Section 3 — Medium (Questions 11–20)

---

## ❓ Question 11

---

| | |
|---|---|
| **Question #** | 11 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior |

### 🏢 Business Scenario

The Finance team wants a **payment method vs. order status revenue matrix**. They need a pivot table showing the **total revenue** (`amount_inr`) for each combination of `payment_method` (rows) and `order_status` (columns). Missing combinations should show **0**, and the matrix should be sorted by the **total row sum** in descending order (highest-earning payment method first).

### 📝 Problem Statement

From the `orders` DataFrame:

1. Build a **pivot table** with:
   - `index = payment_method`
   - `columns = order_status`
   - `values = amount_inr`
   - `aggfunc = sum`
2. Fill any `NaN` cells with `0`
3. Add a new column `row_total` = sum across all status columns (axis=1)
4. Sort by `row_total` descending
5. Round all values to 2 decimal places

### ✅ Requirements

- Use `pd.pivot_table()`
- Use `fillna(0)` after pivoting
- Compute `row_total` using `.sum(axis=1)` — do NOT use a loop
- Round the entire DataFrame using `.round(2)`

### 📊 Expected Output Format

| payment_method | Cancelled | Delivered | Pending | Processing | Returned | Shipped | row_total |
|---|---|---|---|---|---|---|---|
| Credit Card | 0.0 | ... | ... | ... | ... | ... | ... |
| Debit Card | ... | ... | ... | ... | ... | ... | ... |
| ... | | | | | | | |

### 🧠 Concepts Tested

```
Pivot Table  +  fillna  +  Row-wise Sum (axis=1)  +  Sorting  +  round()
```

In [85]:
# Step1: Make Copy

result = orders.copy()

# Step2: Create the pivot table

result = pd.pivot_table(
    data=result,
    index="payment_method",
    columns="order_status",
    values="amount_inr",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

# Step3: Final

result = result.sort_values(
    by="All",
    ascending=False,
    axis=0
).round(2)


display(result)

order_status,Cancelled,Delivered,Pending,Processing,Returned,Shipped,All
payment_method,,,,,,,
All,2396034.0,3476117.0,618016.0,653302.0,547738.0,1341599.0,9032806.0
Debit Card,913958.0,741228.0,126874.0,366969.0,397272.0,130861.0,2677162.0
Credit Card,311474.0,802091.0,38580.0,59388.0,19996.0,735438.0,1966967.0
UPI,344643.0,1149718.0,52572.0,95983.0,67979.0,193557.0,1904452.0
EMI,629993.0,433952.0,0.0,23976.0,2499.0,12994.0,1103414.0
Cash on Delivery,95981.0,243574.0,399990.0,14990.0,59992.0,170973.0,985500.0
Net Banking,99985.0,105554.0,0.0,91996.0,0.0,97776.0,395311.0

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `pd.pivot_table(df, values=..., index=..., columns=..., aggfunc=...)` is the primary function here.
- After pivoting, the column index will have a name (`order_status`) — this is normal; you can leave it or rename it.
- `fillna(0)` fills every NaN cell with zero. Apply it immediately after the pivot.
- To add `row_total`, use `df["row_total"] = df.sum(axis=1)` — but be careful: only sum the status columns, not `row_total` itself if it already exists.
- Sort by `row_total` after computing it.

</details>

---

## ❓ Question 12

---

| | |
|---|---|
| **Question #** | 12 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior |

### 🏢 Business Scenario

The Product team wants a **category-level price analysis**. The `products.category` column has inconsistent casing (`"electronics"`, `"Electronics"`, `"Mobile"`, `"mobile"`) that must be standardized first. Then, for each standardized category, they need the **average price**, **min price**, **max price**, and **count of products** — but only for categories that have **at least 3 products** with a **known price**.

### 📝 Problem Statement

From the `products` DataFrame:

1. **Clean** the `category` column: strip whitespace and convert to **Title Case**
2. Filter rows where `price_inr` is **not null**
3. Group by `category` and compute:
   - `avg_price` — mean of `price_inr`, rounded to 2 decimal places
   - `min_price` — minimum `price_inr`
   - `max_price` — maximum `price_inr`
   - `product_count` — count of products
4. Filter to keep only categories where `product_count >= 3`
5. Sort by `avg_price` descending
6. Reset index

### ✅ Requirements

- Use `.str.strip().str.title()` to standardize categories
- Filter nulls before grouping
- Post-aggregation filter on `product_count`

### 📊 Expected Output Format

| category | avg_price | min_price | max_price | product_count |
|---|---|---|---|---|
| Electronics | ... | ... | ... | ... |
| Mobile | ... | ... | ... | ... |
| ... | | | | |

### 🧠 Concepts Tested

```
String Cleaning  +  Boolean Filtering (null)  +  GroupBy  +  Named Aggregation  +  Post-Aggregation Filtering  +  Sorting
```

In [92]:
# Step1: Make copy of Data

result = products.copy()

# Step2: Cleaning of Products DF

result['category'] = result['category'].str.title().str.strip()

# Step3: Filtering price

result = result[result['price_inr'].notna()]

# Step4: Grouping and Aggregating

result = result.groupby('category').agg(
    avg_price = ('price_inr','mean'),
    min_price = ('price_inr','min'),
    max_price = ('price_inr','max'),
    product_count = ('category', 'count')
).round({'avg_price' : 2}).query('product_count>=3').sort_values(by='avg_price',
                                                                 ascending=False)

display(result)

             avg_price  min_price  max_price  product_count
category
Electronics   23499.00     1499.0    89999.0              6
Audio          8999.00     4999.0    15999.0              4
Mobile         6041.86      999.0    22999.0              7
Accessories    2211.50      599.0     5999.0              8

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Chain `.str.strip()` and `.str.title()` in one step, and assign the result back to the column.
- Filter out rows where `price_inr` is null using `notna()` or `~isna()` **before** grouping.
- Named aggregation syntax: `groupby(...).agg(col_name=("source_col", "func"))`.
- The `product_count >= 3` filter is applied to the **aggregated** DataFrame, not the raw one.
- Think about whether categories with inconsistent casing would merge correctly after `.str.title()` — they should.

</details>

---

## ❓ Question 13

---

| | |
|---|---|
| **Question #** | 13 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior |

### 🏢 Business Scenario

The HR team wants to understand what **percentage of their department's budget** each employee's salary represents. They also want to flag employees whose department manager is **unknown** (missing). The final report should show all employees (even those with missing dept), with missing manager names replaced by `"Manager TBD"` and missing salaries replaced by `0`.

### 📝 Problem Statement

From `employees` (Active only) left-joined with `departments` on `dept_id`:

1. Perform a **left join** so all Active employees are retained (even those with no dept match)
2. Fill missing `manager_name` with `"Manager TBD"`
3. Fill missing `salary_inr` with `0`
4. Compute a new column `salary_pct_of_budget` = (`salary_inr` / `budget_inr`) × 100, rounded to 4 decimal places
   - If `budget_inr` is NaN (no dept match), leave `salary_pct_of_budget` as `NaN`
5. Select: `emp_id`, `employee_name`, `dept_id`, `salary_inr`, `department_name`, `manager_name`, `budget_inr`, `salary_pct_of_budget`
6. Sort by `salary_pct_of_budget` descending (NaN values at the bottom)
7. Reset index

### ✅ Requirements

- Use `how="left"` in `pd.merge()`
- Use `fillna()` selectively on specific columns
- Division by NaN naturally returns NaN — no special handling needed

### 📊 Expected Output Format

| emp_id | employee_name | dept_id | salary_inr | department_name | manager_name | budget_inr | salary_pct_of_budget |
|---|---|---|---|---|---|---|---|
| E... | ... | D07 | 114000.0 | ... | ... | 5000000.0 | 2.28 |
| ... | | | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Merge (Left Join)  +  fillna (column-specific)  +  Arithmetic (percentage)  +  round()  +  Sorting
```

In [12]:
# Step1: Copy employees

result = employees.copy()

# Step2: Filter Active Employees

result = result[result['status'] == 'Active']

# Step3: Clean Departments

dept = departments.copy()

dept['department_name'] = dept['department_name'].str.title()

dept = dept.drop_duplicates(subset='department_name',
                     keep='first',
                     ignore_index=True)


# Step4: Merge clean_employees and clean_Departments

result = pd.merge(result,dept,
         on='dept_id',
         how='left')

# Step5: Keeping useful columns only
result = result[['emp_id','employee_name','dept_id','salary_inr','department_name','manager_name','budget_inr']]

# Step6: Filling missing values

result['salary_inr'] = result['salary_inr'].fillna(0)
result['manager_name'] = result['manager_name'].fillna('Manager TBD')

# Step7: computing pct

result['salary_pct_of_budget'] = ((result['salary_inr']/result['budget_inr'])*100).round(4)

# Step8 : Sort pct

result = result.sort_values(by='salary_pct_of_budget',
                   ascending=False,
                   ignore_index=True,
                   na_position='last')

display(result)

,emp_id,employee_name,dept_id,salary_inr,department_name,manager_name,budget_inr,salary_pct_of_budget
0,E081,Ramesh Sheikh,D04,105000.0,Human Resources,Sunita Rao,2000000.0,5.25
1,E041,Renu Sharma,D04,101000.0,Human Resources,Sunita Rao,2000000.0,5.05
2,E089,Indira Krishnan,D04,99000.0,Human Resources,Sunita Rao,2000000.0,4.95
3,E049,Jyoti Pillai,D04,95000.0,Human Resources,Sunita Rao,2000000.0,4.75
4,E104,Anurag Sinha,D04,95000.0,Human Resources,Sunita Rao,2000000.0,4.75
...,...,...,...,...,...,...,...,...
98,E092,Pramod Yadav,D07,114000.0,NaN,Manager TBD,NaN,NaN
99,E103,Simran Batra,NaN,0.0,NaN,Manager TBD,NaN,NaN
100,E107,Tanmay More,D07,76000.0,NaN,Manager TBD,NaN,NaN
101,E112,Raj Shinde,NaN,78000.0,NaN,Manager TBD,NaN,NaN
102,E115,Sandip Pawar,D07,87000.0,NaN,Manager TBD,NaN,NaN

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Filter for Active employees **before** the merge — this is cleaner.
- `pd.merge(emp_df, dept_df, on="dept_id", how="left")` retains all employees, even those with missing or unmatched `dept_id`.
- Use `df["col"].fillna(value)` to fill a specific column — do NOT use `df.fillna()` which fills all columns.
- The percentage formula: `(salary_inr / budget_inr) * 100` — when `budget_inr` is NaN, the result will naturally be NaN.
- `sort_values(..., na_position="last")` ensures NaN rows appear at the bottom.

</details>

---

## ❓ Question 14

---

| | |
|---|---|
| **Question #** | 14 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior |

### 🏢 Business Scenario

The Operations team wants a **Q1 2024 attendance summary per employee**. They need to identify employees who had an **average attendance rate below 85%** during January–March 2024. Employees with any missing `present_days` data should be **excluded** from the analysis.

### 📝 Problem Statement

From the `attendance` DataFrame:

1. Parse the `month` column as a datetime (format: `YYYY-MM`)
2. Filter to rows where the month is between **January 2024** and **March 2024** (inclusive)
3. Drop rows where `present_days` is null
4. Compute `attendance_rate` = (`present_days` / `working_days`) × 100 per row
5. Group by `emp_id` and compute:
   - `avg_attendance_rate` — mean of `attendance_rate`, rounded to 2 decimal places
   - `total_present_days` — sum of `present_days`
   - `total_overtime_hours` — sum of `overtime_hours` (NaN treated as 0 before summing — use `fillna(0)` before grouping)
6. Filter to employees whose `avg_attendance_rate < 85`
7. Sort by `avg_attendance_rate` ascending (worst attendance first)
8. Reset index

### ✅ Requirements

- Use `pd.to_datetime()` with `format="%Y-%m"` for parsing
- Compute `attendance_rate` as a new column before grouping
- Use `fillna(0)` only on `overtime_hours` before summing

### 📊 Expected Output Format

| emp_id | avg_attendance_rate | total_present_days | total_overtime_hours |
|---|---|---|---|
| E... | 72.73 | ... | ... |
| E... | 77.27 | ... | ... |
| ... | | | |

### 🧠 Concepts Tested

```
Datetime Parsing  +  .dt accessor  +  Boolean Filtering (date range)  +  dropna  +  Computed Column  +  fillna  +  GroupBy  +  Named Aggregation  +  Post-Aggregation Filtering
```

In [24]:
# Step1: Copy Dataset

result = attendance.copy()

# Step2: Convert datetime

result['month'] = pd.to_datetime(result['month'], format='%Y-%m')

# Step3: Filter non present days and quarter 1 only

result = result[(result['present_days'].notna()) & 
                result['month'].dt.month.isin([1,2,3])]

# Step4: Find attendance rate

result['attendance_rate'] = (result['present_days']/result['working_days'])*100

# Step4.1: 

result['overtime_hours'] = result['overtime_hours'].fillna(0)

# Step5: Avg rate

result = result.groupby('emp_id').agg(
    avg_attendance_rate  = ('attendance_rate' , 'mean'),
    total_present_days   = ('present_days','sum'),
    total_overtime_hours = ('overtime_hours','sum')
).reset_index().round({'avg_attendance_rate' : 2 })

# Step6 : Filtering culprits

result = result[result['avg_attendance_rate'] < 85].sort_values(by='avg_attendance_rate',
                                                                ascending = True,
                                                                ignore_index=True)


display(result)

   emp_id  avg_attendance_rate  total_present_days  total_overtime_hours
0    E015                78.79                52.0                  14.0
1    E006                80.30                53.0                  14.0
2    E010                80.30                53.0                  14.0
3    E005                81.82                54.0                   2.0
4    E044                81.82                54.0                   8.0
5    E030                81.82                54.0                   4.0
6    E050                83.33                55.0                  16.0
7    E049                83.33                55.0                   0.0
8    E022                84.09                37.0                   0.0
9    E040                84.09                37.0                   6.0
10   E029                84.85                56.0                  14.0
11   E014                84.85                56.0                   8.0
12   E036                84.85                56.0                  12.0
13   E035                84.85                56.0                  12.0
14   E009                84.85                56.0                   0.0
15   E031                84.85                56.0                   2.0
16   E048                84.85                56.0                   8.0
17   E038                84.85                56.0                   2.0

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `pd.to_datetime(df["month"], format="%Y-%m")` converts strings like `"2024-01"` to proper datetime objects.
- For date range filtering: use `.dt.month` and `.dt.year`, or compare against string timestamps using `pd.Timestamp`.
- Compute `attendance_rate = (present_days / working_days) * 100` as a new column **before** grouping.
- Fill `overtime_hours` nulls with 0 before summing — otherwise NaN propagates and you get NaN sums.
- The `< 85` filter is on the **grouped** result, not on individual rows.

</details>

---

## ❓ Question 15

---

| | |
|---|---|
| **Question #** | 15 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior |

### 🏢 Business Scenario

The Customer Success team wants to identify **high-value repeat customers** — customers whose **cumulative total spend** (running total of `amount_inr` across all their Delivered orders, chronologically) has **exceeded ₹1,00,000** at some point. They want to see each customer's **final cumulative total** and the **order number** at which they crossed the threshold.

### 📝 Problem Statement

From the `orders` DataFrame:

1. Filter to `order_status == "Delivered"` and `amount_inr` is not null
2. Parse `order_date` as datetime
3. Sort by `customer_id` ASC, then `order_date` ASC
4. Compute `cumulative_spend` = cumulative sum of `amount_inr` per `customer_id` (using `groupby` + `transform`)
5. Compute `order_number` = order sequence number per `customer_id` (1st order = 1, 2nd = 2, etc.) using `groupby` + `cumcount` + 1
6. Filter to keep only rows where `cumulative_spend > 100000`
7. For each `customer_id`, keep only the **first** row where they crossed ₹1,00,000 (i.e., `order_number` at first crossing)
8. Select: `customer_id`, `order_id`, `order_date`, `amount_inr`, `order_number`, `cumulative_spend`
9. Sort by `cumulative_spend` descending
10. Reset index

### ✅ Requirements

- Use `groupby().transform("cumsum")` for cumulative spend
- Use `groupby().cumcount()` + 1 for order sequence
- Use `drop_duplicates(subset="customer_id", keep="first")` to get first crossing
- No loops, no apply

### 📊 Expected Output Format

| customer_id | order_id | order_date | amount_inr | order_number | cumulative_spend |
|---|---|---|---|---|---|
| C... | O... | 20xx-xx-xx | ... | 3 | 110000.0 |
| ... | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Datetime Parsing  +  Sorting  +  GroupBy + Transform (cumsum)  +  GroupBy + cumcount  +  Filtering  +  drop_duplicates
```

In [44]:
# Step1: Copy Dataset

result = orders.copy()

# Step2: Keep only Delivered orders with non-null amount

result = result[
    (result['order_status'] == 'Delivered') &
    (result['amount_inr'].notna())
]

# Step3: Convert order_date to datetime

result['order_date'] = pd.to_datetime(result['order_date'])

# Step4: Sort by customer and order date

result = result.sort_values(
    by=['customer_id', 'order_date'],
    ignore_index=True
)

# Step5: Compute cumulative spend

result['cumulative_spend'] = result.groupby('customer_id')['amount_inr'] \
                                   .transform('cumsum')

# Step6: Compute order number

result['order_number'] = result.groupby('customer_id').cumcount() + 1


# Step7: Keep only rows where cumulative spend crossed ₹1,00,000

result = result[result['cumulative_spend'] > 100000]

# Step8: Keep first crossing per customer

result = result.drop_duplicates(
    subset='customer_id',
    keep='first'
)

# Step9: Keep useful columns only

result = result[
    ['customer_id', 'order_id', 'order_date',
     'amount_inr', 'order_number', 'cumulative_spend']
]

# Step10: Sort and reset index

result = result.sort_values(
    by='cumulative_spend',
    ascending=False,
    ignore_index=True
)

display(result)

  customer_id order_id order_date  amount_inr  order_number  cumulative_spend
0        C051    O0164 2022-10-23    449995.0             1          449995.0
1        C043    O0077 2023-08-27    449995.0             1          449995.0
2        C028    O0016 2022-09-12    249990.0             1          249990.0
3        C007    O0052 2023-07-20    143991.0             2          218988.0
4        C024    O0092 2022-06-19    209994.0             1          209994.0
5        C049    O0182 2022-01-02    206991.0             1          206991.0
6        C026    O0151 2023-04-27    199995.0             1          199995.0
7        C017    O0174 2022-09-16    179998.0             1          179998.0
8        C030    O0108 2023-05-28     22491.0             3          112479.0

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `groupby("customer_id")["amount_inr"].transform("cumsum")` computes a running total per customer, aligned back to the original DataFrame.
- `groupby("customer_id").cumcount()` returns 0-indexed sequence numbers per group — add 1 to start from 1.
- The sort order matters: sort by `customer_id` and `order_date` **before** computing cumsum and cumcount, so the running total is in chronological order.
- After filtering `cumulative_spend > 100000`, use `drop_duplicates(subset="customer_id", keep="first")` to retain only the first row where each customer crossed the threshold.
- The data is already sorted chronologically, so "first" in `drop_duplicates` correctly means "first crossing".

</details>

---

## ❓ Question 16

---

| | |
|---|---|
| **Question #** | 16 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior-to-Mid |

### 🏢 Business Scenario

The Supply Chain team wants to understand **revenue by vendor** — which vendors' products are generating the most revenue from Delivered orders. They need to join three tables: `orders`, `products`, and `vendors`.

### 📝 Problem Statement

1. Filter `orders` to `order_status == "Delivered"` and `amount_inr` not null
2. Merge filtered orders with `products` on `product_id` (inner join)
3. Clean `vendors.vendor_name` — strip whitespace, convert to Title Case
4. Merge the result with `vendors` on `vendor_id` (inner join)
5. Group by `vendor_id` and `vendor_name`, compute:
   - `total_orders` — count of orders
   - `total_revenue` — sum of `amount_inr`
   - `unique_products_sold` — count of distinct `product_id` values
   - `avg_order_value` — mean of `amount_inr`, rounded to 2 decimal places
6. Sort by `total_revenue` descending
7. Reset index

### ✅ Requirements

- Perform two sequential merges
- Clean vendor names before the second merge
- Use `nunique()` for unique products sold

### 📊 Expected Output Format

| vendor_id | vendor_name | total_orders | total_revenue | unique_products_sold | avg_order_value |
|---|---|---|---|---|---|
| V... | ... | ... | ... | ... | ... |
| ... | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Two Sequential Merges  +  String Cleaning  +  GroupBy  +  Multiple Aggregations (sum, count, nunique, mean)  +  Sorting
```

In [49]:
# Step1: Copy Datasets

result = orders.copy()
prod = products.copy()
vendor = vendors.copy()

# Step2: Filter Delivered orders with non-null amount

result = result[
    (result['order_status'] == 'Delivered') &
    (result['amount_inr'].notna())
]

# Step3: Merge orders with products

result = pd.merge(
    result,
    prod,
    on='product_id',
    how='inner'
)

# Step4: Clean vendor names

vendor['vendor_name'] = vendor['vendor_name'].str.strip().str.title()

# Step5: Merge with vendors

result = pd.merge(
    result,
    vendor,
    on='vendor_id',
    how='inner'
)

# Step6: Compute vendor summary

result = result.groupby(
    ['vendor_id', 'vendor_name']
).agg(
    total_orders=('order_id', 'count'),
    total_revenue=('amount_inr', 'sum'),
    unique_products_sold=('product_id', 'nunique'),
    avg_order_value=('amount_inr', 'mean')
).round({
    'avg_order_value': 2
})

# Step7: Sort and reset index

result = result.sort_values(
    by='total_revenue',
    ascending=False
).reset_index()

display(result)

,vendor_id,vendor_name,total_orders,total_revenue,unique_products_sold,avg_order_value
0,V007,Mobilezone,12,768833.0,6,64069.42
1,V001,Techworld Supplies,8,705559.0,3,88194.88
2,V008,Gadgetfirst,6,610960.0,3,101826.67
3,V004,Audiomax Ltd,9,377454.0,4,41939.33
4,V002,Digitalhub Pvt Ltd,8,364259.0,4,45532.38
5,V006,Connectkart,10,336045.0,2,33604.50
6,V003,Storagepro Inc,14,210826.0,4,15059.00
7,V005,Officepro Furniture,5,102181.0,3,20436.20

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Do the filtering first, then chain the merges: `orders → products → vendors`.
- Clean the `vendor_name` column in the `vendors` DataFrame **before** the second merge — this avoids dirty names in the result.
- After both merges, group by both `vendor_id` and `vendor_name` together (as a multi-column groupby) so the vendor name appears in the result.
- `nunique()` counts distinct values per group — pass `"product_id"` as the column to count distinct products.
- Remember: an inner join with vendors will drop any products whose `vendor_id` does not exist in `vendors.csv`.

</details>

---

## ❓ Question 17

---

| | |
|---|---|
| **Question #** | 17 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior-to-Mid |

### 🏢 Business Scenario

The HR Head wants a **department × status headcount matrix** — a table where rows are departments, columns are employment statuses (Active, Inactive, Resigned), and each cell shows the number of employees in that combination. A `Grand Total` column should show the total headcount per department. The result should be sorted by `Grand Total` descending.

### 📝 Problem Statement

From `employees` (after dropping duplicate `emp_id` rows — keep first):

1. Drop duplicate rows based on `emp_id` (keep first)
2. Build a **pivot table** with:
   - `index = dept_id`
   - `columns = status`
   - `values = emp_id`
   - `aggfunc = "count"`
3. Fill NaN with `0`, convert all values to `int`
4. Add a `Grand Total` column = sum of all status columns per row
5. Sort by `Grand Total` descending
6. Rename the column index name to `None` (remove the header "status") for clean output

### ✅ Requirements

- Deduplicate by `emp_id` before pivoting
- Use `pd.pivot_table()` with `aggfunc="count"`
- Fill NaN with `0` and convert to `int` using `.astype(int)`
- Add `Grand Total` using `.sum(axis=1)` — do NOT include `Grand Total` in its own sum

### 📊 Expected Output Format

| dept_id | Active | Inactive | Resigned | Grand Total |
|---|---|---|---|---|
| D01 | ... | ... | ... | ... |
| D03 | ... | ... | ... | ... |
| ... | | | | |

### 🧠 Concepts Tested

```
Drop Duplicates  +  Pivot Table (count aggfunc)  +  fillna + astype  +  Row-wise Sum (axis=1)  +  Column Rename  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Deduplicate by `emp_id` **before** the pivot to avoid counting the same employee twice.
- `pd.pivot_table(df, values="emp_id", index="dept_id", columns="status", aggfunc="count")` counts occurrences per cell.
- After `fillna(0)`, use `.astype(int)` to convert float zeros to integers.
- Compute `Grand Total = df.sum(axis=1)` and assign it as a new column. Do this before any sorting.
- To remove the column index name ("status"), set `df.columns.name = None`.

</details>

---

## ❓ Question 18

---

| | |
|---|---|
| **Question #** | 18 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior-to-Mid |

### 🏢 Business Scenario

The Inventory team wants to understand **stock distribution across product categories**. After standardizing the messy `category` column, they need the **total stock per category** and the **percentage share of total stock** that each category holds. Categories with missing `stock_quantity` should be **excluded** from the analysis.

### 📝 Problem Statement

From the `products` DataFrame:

1. **Clean** the `category` column: strip spaces, convert to Title Case
2. Filter rows where `stock_quantity` is **not null**
3. Group by `category` and compute:
   - `total_stock` — sum of `stock_quantity`
   - `product_count` — count of products
   - `avg_stock` — mean of `stock_quantity`, rounded to 2 decimal places
4. Compute a new column `stock_share_pct` = (`total_stock` / sum of all `total_stock`) × 100, rounded to 2 decimal places
5. Sort by `stock_share_pct` descending
6. Reset index

### ✅ Requirements

- Compute `stock_share_pct` on the **aggregated** DataFrame (not on raw data)
- Use `.sum()` on the `total_stock` column of the result to compute the denominator
- All percentage values must sum to ~100%

### 📊 Expected Output Format

| category | total_stock | product_count | avg_stock | stock_share_pct |
|---|---|---|---|---|
| Accessories | ... | ... | ... | 38.xx% |
| Electronics | ... | ... | ... | 22.xx% |
| ... | | | | |

### 🧠 Concepts Tested

```
String Cleaning  +  Boolean Filtering (null)  +  GroupBy  +  Named Aggregation  +  Post-Aggregation Arithmetic (percentage)  +  round()  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- The category standardization must happen **before** any filtering or grouping.
- After groupby aggregation, you have a DataFrame with `total_stock` as a column.
- To compute the share: `result["total_stock"] / result["total_stock"].sum() * 100`.
- Apply `.round(2)` to the final `stock_share_pct` column.
- Verify your percentages sum to approximately 100 — a quick sanity check is `result["stock_share_pct"].sum()`.

</details>

---

## ❓ Question 19

---

| | |
|---|---|
| **Question #** | 19 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior-to-Mid |

### 🏢 Business Scenario

The Operations Head wants a **department-level attendance health report** for the first half of 2024 (January–June). They want to see, per department: the **average attendance rate** across all employees and months, the **total overtime hours**, and the **number of employees contributing data**. Only **Active employees** should be included. Departments where the **average attendance rate falls below 90%** should be flagged as at-risk.

### 📝 Problem Statement

1. Parse `attendance.month` as datetime
2. Filter `attendance` to months in 2024 only
3. Drop rows where `present_days` is null
4. Compute `attendance_rate` = (`present_days` / `working_days`) × 100
5. Fill `overtime_hours` null values with `0`
6. Merge the attendance data with `employees` (Active only) on `emp_id` using an **inner join**
7. Merge the result with `departments` on `dept_id` using an **inner join** to get `department_name`
8. Group by `department_name` and compute:
   - `avg_attendance_rate` — mean of `attendance_rate`, rounded to 2 decimal places
   - `total_overtime_hours` — sum of `overtime_hours`
   - `employee_count` — count of distinct `emp_id` values
9. Add a boolean column `at_risk` = True where `avg_attendance_rate < 90`
10. Sort by `avg_attendance_rate` ascending
11. Reset index

### ✅ Requirements

- Filter employees for Active status before merging
- Use `nunique()` for `employee_count`
- Add `at_risk` as a boolean comparison column

### 📊 Expected Output Format

| department_name | avg_attendance_rate | total_overtime_hours | employee_count | at_risk |
|---|---|---|---|---|
| Engineering | 82.xx | ... | ... | True |
| Sales | 88.xx | ... | ... | True |
| ... | | | | |

### 🧠 Concepts Tested

```
Datetime Parsing  +  Boolean Filtering  +  dropna  +  Computed Column  +  fillna  +  Two Sequential Merges (Inner)  +  GroupBy  +  Multiple Aggregations  +  Boolean Column Creation  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- The order matters: parse datetime → filter → drop nulls → compute columns → merge.
- Use `.dt.year == 2024` to filter only 2024 months.
- The inner join with Active employees will automatically exclude employees who are not in the Active filter — this is by design.
- After the second merge (with departments), some employees may lose records if their dept_id doesn't exist in departments — this is expected for an inner join.
- To create the `at_risk` boolean column: `result["at_risk"] = result["avg_attendance_rate"] < 90`. This produces a True/False column directly.

</details>

---

## ❓ Question 20

---

| | |
|---|---|
| **Question #** | 20 of 50 |
| **Difficulty** | 🟠 Medium |
| **Interview Level** | Junior-to-Mid |

### 🏢 Business Scenario

The Finance team wants to see the **Top 2 months by total transaction amount for each transaction type** (Credit, Debit, Refund, Transfer). The `transactions.category` column has inconsistent casing (e.g., `"PURCHASE"`, `"purchase"`, `"Purchase"`) — the team wants the category standardized as part of the output. Only **Successful** transactions with a **known amount** should be included.

### 📝 Problem Statement

From the `transactions` DataFrame:

1. Filter to `txn_status == "Success"` and `amount_inr` is not null
2. Clean the `category` column: strip spaces, convert to Title Case
3. Parse `txn_date` as datetime, extract the **month-year** as a string column `txn_month` in format `YYYY-MM` (using `.dt.to_period("M").astype(str)`)
4. Group by `txn_type` and `txn_month`, compute:
   - `total_amount` — sum of `amount_inr`, rounded to 2 decimal places
   - `transaction_count` — count of transactions
5. Within each `txn_type`, **rank** `total_amount` in **descending** order (dense rank)
6. Filter to keep only rows where rank <= 2
7. Select: `txn_type`, `txn_month`, `total_amount`, `transaction_count`, `rank`
8. Convert rank to int
9. Sort by `txn_type` ASC, `rank` ASC
10. Reset index

### ✅ Requirements

- Use `.dt.to_period("M").astype(str)` for month extraction
- Use `groupby().rank(method="dense", ascending=False)` on the **aggregated** result
- No loops, no apply

### 📊 Expected Output Format

| txn_type | txn_month | total_amount | transaction_count | rank |
|---|---|---|---|---|
| Credit | 2023-xx | ... | ... | 1 |
| Credit | 2022-xx | ... | ... | 2 |
| Debit | 2023-xx | ... | ... | 1 |
| ... | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  String Cleaning  +  Datetime Parsing  +  Period Extraction  +  GroupBy  +  Named Aggregation  +  GroupBy Rank (Dense)  +  Type Casting  +  Multi-column Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Filter and clean **before** any date parsing or grouping.
- `pd.to_datetime(df["txn_date"]).dt.to_period("M").astype(str)` converts each date to its month period string like `"2023-04"`.
- Group by **both** `txn_type` and `txn_month` to get monthly totals per transaction type.
- After aggregation, use `groupby("txn_type")["total_amount"].rank(method="dense", ascending=False)` on the **grouped result DataFrame** to rank months within each type.
- The rank column will be float — convert to int after filtering to rank <= 2.
- This is a two-level groupby pattern: group for aggregation, then group again for ranking.

</details>

---
---

# 🔴 Section 4 — Medium-Hard (Questions 21–30)

---

## ❓ Question 21

---

| | |
|---|---|
| **Question #** | 21 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The Compensation team wants a **salary band distribution matrix** — showing, for each department, how many Active employees fall into each salary bracket. This helps them spot departments that are top-heavy or underpaying. Employees with missing salaries should be **excluded**.

### 📝 Problem Statement

From the `employees` DataFrame (Active + non-null salary, deduplicated by `emp_id`):

1. Drop duplicate `emp_id` rows (keep first)
2. Filter: Active status + non-null `salary_inr`
3. Create a new column `salary_band` using `pd.cut()` with these bins and labels:
   - Below ₹60,000 → `"<60K"`
   - ₹60,000–₹80,000 → `"60K-80K"`
   - ₹80,000–₹1,00,000 → `"80K-100K"`
   - Above ₹1,00,000 → `">100K"`
4. Group by `dept_id` and `salary_band`, count employees
5. **Unstack** `salary_band` as columns
6. Fill NaN with `0`, convert all to `int`
7. Add a `total_employees` column = sum across all band columns
8. Sort by `total_employees` descending

### ✅ Requirements

- Use `pd.cut(bins=[0, 60000, 80000, 100000, float("inf")], labels=[...])` — this is a Pandas function
- Use `.unstack()` to reshape — no pivot_table
- Use `.fillna(0).astype(int)` after unstack
- Add `total_employees` using `.sum(axis=1)` on the band columns only

### 📊 Expected Output Format

| dept_id | <60K | 60K-80K | 80K-100K | >100K | total_employees |
|---|---|---|---|---|---|
| D01 | 0 | 3 | 5 | 2 | 10 |
| D02 | 1 | 4 | 3 | 1 | 9 |
| ... | | | | | |

### 🧠 Concepts Tested

```
Drop Duplicates  +  Boolean Filtering  +  pd.cut (Binning)  +  GroupBy  +  unstack  +  fillna + astype  +  Row-wise Sum  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `pd.cut(series, bins=[0, 60000, 80000, 100000, float("inf")], labels=["<60K","60K-80K","80K-100K",">100K"])` assigns each salary to a labeled bin.
- After `groupby(["dept_id","salary_band"]).size()`, you get a multi-index Series. Calling `.unstack("salary_band")` pivots it so `salary_band` values become columns.
- `.fillna(0).astype(int)` cleans up the NaN cells that appear for missing combinations.
- Compute `total_employees` by summing across the band columns — use `.sum(axis=1)` on the DataFrame.
- Remember to remove the column axis name for clean output: `df.columns.name = None`.

</details>

---

## ❓ Question 22

---

| | |
|---|---|
| **Question #** | 22 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The Finance team wants to track **Month-over-Month (MoM) revenue growth** from Delivered orders. They need a table showing each month's total revenue, the previous month's revenue, and the percentage change — so leadership can spot which months saw a spike or a drop.

### 📝 Problem Statement

From the `orders` DataFrame:

1. Filter: `order_status == "Delivered"` and `amount_inr` not null
2. Parse `order_date` as datetime; extract `order_month` as period string `"YYYY-MM"` (use `.dt.to_period("M").astype(str)`)
3. Group by `order_month`, compute:
   - `total_revenue` — sum of `amount_inr`
   - `order_count` — count of orders
4. Sort by `order_month` ascending
5. Add `prev_month_revenue` = `total_revenue` shifted by 1 row (use `.shift(1)`)
6. Compute `mom_growth_pct` = (`total_revenue` − `prev_month_revenue`) / `prev_month_revenue` × 100, rounded to 2 decimal places
7. Round `total_revenue` to 2 decimal places
8. Reset index

### ✅ Requirements

- Use `.dt.to_period("M").astype(str)` for month extraction
- Use `.shift(1)` on the aggregated Series — NOT on raw data
- First month will have `NaN` for `prev_month_revenue` and `mom_growth_pct` — leave as NaN

### 📊 Expected Output Format

| order_month | total_revenue | order_count | prev_month_revenue | mom_growth_pct |
|---|---|---|---|---|
| 2022-01 | ... | ... | NaN | NaN |
| 2022-02 | ... | ... | ... | +12.34 |
| ... | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Datetime Parsing  +  Period Extraction  +  GroupBy  +  Named Aggregation  +  Sorting  +  shift()  +  Arithmetic (MoM %)  +  round()
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- After grouping and aggregating, your result is a DataFrame sorted by `order_month`.
- `.shift(1)` on the `total_revenue` column moves every value down by one row — the first row gets `NaN` naturally.
- MoM growth formula: `(total_revenue - prev_month_revenue) / prev_month_revenue * 100`.
- Division by NaN (for the first row) naturally produces NaN — no special handling needed.
- Sort **before** computing `shift()` — otherwise the shift will be in the wrong order.

</details>

---

## ❓ Question 23

---

| | |
|---|---|
| **Question #** | 23 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The Customer Analytics team wants to identify **lapsed customers** — customers who placed at least one order in **2022** but have placed **zero orders** in **2023 or 2024**. These customers need to be targeted for a re-engagement campaign. The report should include their last order date and total historical spend.

### 📝 Problem Statement

From the `orders` DataFrame (only Delivered orders with non-null `amount_inr`):

1. Parse `order_date` as datetime; extract `order_year` using `.dt.year`
2. Find the set of `customer_id`s who ordered **at least once in 2022**
3. Find the set of `customer_id`s who ordered **at least once in 2023 or 2024**
4. Lapsed customers = those in the 2022 set but **NOT** in the 2023/2024 set
   - Use Pandas boolean filtering with `.isin()` — no Python sets or loops
5. For lapsed customers, compute (from **all** their Delivered orders, not just 2022):
   - `last_order_date` — max of `order_date`
   - `total_orders` — count of orders
   - `total_spend` — sum of `amount_inr`, rounded to 2 decimal places
6. Sort by `total_spend` descending
7. Reset index

### ✅ Requirements

- Use `.isin()` for all set-membership checks — no Python `set()`, no loops
- The "all Delivered orders" in step 5 means filter by `order_status == "Delivered"` and `amount_inr` not null, then filter by the lapsed `customer_id` list

### 📊 Expected Output Format

| customer_id | last_order_date | total_orders | total_spend |
|---|---|---|---|
| C... | 2022-xx-xx | ... | ... |
| ... | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Datetime + .dt.year  +  isin()  +  Negation (~)  +  Two-stage Customer ID Filtering  +  GroupBy  +  Named Aggregation  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- To get the set of 2022 customers: filter `order_year == 2022`, then use `.unique()` or just the Series directly with `.isin()`.
- To get the 2023/2024 customers: filter `order_year.isin([2023, 2024])`.
- Lapsed = in 2022 group AND NOT in 2023/2024 group. Use `isin(customers_2022) & ~isin(customers_2023_24)`.
- A cleaner approach: get the two customer ID Series, then filter the 2022 IDs using `~isin(ids_2023_24)`.
- For the final aggregation, filter the full Delivered orders DataFrame using `.isin(lapsed_ids)`, then group by `customer_id`.

</details>

---

## ❓ Question 24

---

| | |
|---|---|
| **Question #** | 24 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The Data Quality team has flagged that the `orders` dataset contains **true business duplicates** — cases where the same `customer_id` ordered the same `product_id` on the same `order_date` with the same `amount_inr`. They want a report showing:
1. Which (customer, product, date) combinations are duplicated
2. How many times each duplicate appears
3. The **total inflated revenue** caused by these duplicates (i.e., the revenue counted more than once)

### 📝 Problem Statement

From the `orders` DataFrame:

1. Identify duplicate records based on: `customer_id`, `product_id`, `order_date`, `amount_inr` (all four must match)
2. Group the duplicated records by these four columns and compute:
   - `duplicate_count` — total number of records in each duplicate group
   - `excess_count` — number of **extra** copies (duplicate_count − 1)
   - `inflated_revenue` — `amount_inr` × `excess_count` (the revenue double-counted)
3. Filter to groups where `duplicate_count >= 2`
4. Sort by `inflated_revenue` descending
5. Reset index
6. At the end, print the **total inflated revenue** across all duplicate groups (sum of `inflated_revenue`)

### ✅ Requirements

- Use `duplicated(subset=[...], keep=False)` to flag ALL rows that are part of a duplicate group
- Then `groupby` the same subset columns to aggregate
- No loops, no apply

### 📊 Expected Output Format

| customer_id | product_id | order_date | amount_inr | duplicate_count | excess_count | inflated_revenue |
|---|---|---|---|---|---|---|
| C... | P... | 20xx-xx-xx | ... | 2 | 1 | ... |
| ... | | | | | | |

`Total inflated revenue: ₹xxxxxx`

### 🧠 Concepts Tested

```
duplicated(keep=False)  +  Boolean Filtering  +  GroupBy  +  Named Aggregation  +  Computed Column (arithmetic)  +  Sorting  +  Scalar Output (sum)
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `df.duplicated(subset=["customer_id","product_id","order_date","amount_inr"], keep=False)` returns a boolean Series — `True` for EVERY row that belongs to a duplicate group (both the original and its copies).
- Filter the DataFrame using this boolean mask to get only the duplicated rows.
- Then group by the same 4 columns and use `.size()` to count occurrences in each group.
- `excess_count = duplicate_count - 1` tells you how many extra copies exist.
- `inflated_revenue = amount_inr * excess_count` — since `amount_inr` is the same within each group, this is straightforward arithmetic.
- After building the result DataFrame, `.sum()` on `inflated_revenue` gives the total impact.

</details>

---

## ❓ Question 25

---

| | |
|---|---|
| **Question #** | 25 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The CRM team wants to classify orders as belonging to **New** or **Returning** customers. A "New" order is a customer's **very first** Delivered order ever. Every subsequent Delivered order from the same customer is "Returning". The team wants a **monthly breakdown** of revenue from New vs Returning customers to see how acquisition and retention are trending.

### 📝 Problem Statement

From `orders` (Delivered + non-null `amount_inr`):

1. Parse `order_date` as datetime
2. For each `customer_id`, find their **first ever order date** using `groupby + transform("min")`
3. Create column `customer_type`:
   - `"New"` if `order_date == first_order_date`
   - `"Returning"` otherwise
   - Use `pd.Series.where()` or boolean masking — no `apply()`
4. Extract `order_month` as `"YYYY-MM"` period string
5. Group by `order_month` and `customer_type`, compute:
   - `total_revenue` — sum of `amount_inr`, rounded to 2 decimal places
   - `order_count` — count of orders
6. **Unstack** `customer_type` as columns (so `New` and `Returning` become column pairs)
7. Fill NaN with `0`
8. Sort by `order_month` ascending
9. Reset index

### ✅ Requirements

- Use `groupby("customer_id")["order_date"].transform("min")` for first order date
- Use boolean masking with `pd.Series.where()` or `numpy`-free string assignment for `customer_type`
- Use `.unstack()` — no `pivot_table()`

### 📊 Expected Output Format (after unstack)

```
customer_type   New                  Returning
                total_revenue  ...   total_revenue  ...
order_month
2022-01         ...            ...   ...            ...
```

### 🧠 Concepts Tested

```
Boolean Filtering  +  Datetime Parsing  +  GroupBy + Transform(min)  +  Conditional Column (where/mask)  +  Period Extraction  +  GroupBy  +  unstack  +  fillna  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `groupby("customer_id")["order_date"].transform("min")` broadcasts each customer's earliest order date back to every row — making it possible to compare row-by-row.
- For `customer_type`: `df["customer_type"] = "Returning"` first, then `df.loc[df["order_date"] == df["first_order_date"], "customer_type"] = "New"` — this is pure Pandas boolean assignment.
- Or use: `(df["order_date"] == df["first_order_date"]).map({True: "New", False: "Returning"})`
- After groupby + unstack, your columns will be a MultiIndex — this is expected. You can leave it or flatten it with `df.columns = ["_".join(c) for c in df.columns]`.
- `fillna(0)` fills missing combinations (e.g., a month with no New customers).

</details>

---

## ❓ Question 26

---

| | |
|---|---|
| **Question #** | 26 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The Product team wants to understand which **products are generating the most revenue within each standardized product category**, using only Delivered orders. They want a **category-level product ranking**, and only the **Top 2 products per category** by revenue. Products that were never ordered should still appear — with zero revenue and a null rank.

### 📝 Problem Statement

1. Clean `products.category`: strip + Title Case
2. Aggregate `orders` (Delivered + non-null `amount_inr`) by `product_id`:
   - `total_revenue` — sum of `amount_inr`
   - `total_units_sold` — sum of `quantity`
3. **Left join** the aggregated orders onto `products` (so all products appear, even unordered ones)
4. Fill missing `total_revenue` and `total_units_sold` with `0`
5. Within each `category`, **dense rank** products by `total_revenue` descending
   - Store as `revenue_rank` (int)
6. Filter to keep only rows where `revenue_rank <= 2`
7. Select: `category`, `product_id`, `product_name`, `price_inr`, `total_revenue`, `total_units_sold`, `revenue_rank`
8. Sort by `category` ASC, `revenue_rank` ASC
9. Reset index

### ✅ Requirements

- Aggregate orders first, **then** left join onto products (products is the left table)
- Use `groupby().rank(method="dense", ascending=False)` after the merge
- `fillna(0)` before ranking so that unordered products get rank based on 0 revenue

### 📊 Expected Output Format

| category | product_id | product_name | price_inr | total_revenue | total_units_sold | revenue_rank |
|---|---|---|---|---|---|---|
| Accessories | P... | ... | ... | ... | ... | 1 |
| Accessories | P... | ... | ... | ... | ... | 2 |
| Audio | P... | ... | ... | ... | ... | 1 |
| ... | | | | | | |

### 🧠 Concepts Tested

```
String Cleaning  +  GroupBy Aggregation (orders)  +  Left Merge (products as base)  +  fillna  +  GroupBy + Dense Rank  +  Filter  +  Column Selection  +  Multi-column Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Think of it in two phases: (1) summarize orders, (2) join onto products.
- `orders.groupby("product_id").agg(...)` gives you one row per product with revenue totals.
- Then `pd.merge(products, order_summary, on="product_id", how="left")` — products is the **left** table so all 30 products appear.
- `fillna(0)` ensures products with no orders get `total_revenue = 0` before ranking.
- `groupby("category")["total_revenue"].rank(method="dense", ascending=False)` computes rank within each category.
- Convert rank to int, filter `<= 2`, then select and sort.

</details>

---

## ❓ Question 27

---

| | |
|---|---|
| **Question #** | 27 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The Finance Controller wants to audit the **transactions dataset for category inconsistencies and anomalies**. Specifically, they want to know: for each **standardized transaction category**, what is the **total amount for each transaction type**, and which category-type combinations are **statistical outliers** (i.e., their total amount is more than **1.5 × IQR above Q3** of all totals for that transaction type).

### 📝 Problem Statement

From the `transactions` DataFrame (Successful + non-null `amount_inr`):

1. Clean `category`: strip + Title Case
2. Group by `txn_type` and `category`, compute:
   - `total_amount` — sum of `amount_inr`, rounded to 2 decimal places
   - `txn_count` — count of transactions
3. Reset index
4. For each `txn_type`, compute IQR-based outlier bounds:
   - `q1` = 25th percentile of `total_amount` within that `txn_type`
   - `q3` = 75th percentile of `total_amount` within that `txn_type`
   - `iqr` = q3 − q1
   - `upper_bound` = q3 + 1.5 × iqr
   - Add these as columns using `groupby + transform` with `quantile()`
5. Add boolean column `is_outlier` = True where `total_amount > upper_bound`
6. Sort by `txn_type` ASC, `total_amount` DESC

### ✅ Requirements

- Use `groupby().transform(lambda s: s.quantile(0.25))` for Q1 — but since `lambda` is not `apply()` on the DataFrame level, this is acceptable: you are using it as a `transform` function specifier. **Alternative:** use `groupby().transform("quantile", 0.25)` if your Pandas version supports it.
- No loops, no iterrows

### 📊 Expected Output Format

| txn_type | category | total_amount | txn_count | q1 | q3 | iqr | upper_bound | is_outlier |
|---|---|---|---|---|---|---|---|---|
| Credit | Purchase | ... | ... | ... | ... | ... | ... | False |
| Credit | Salary | ... | ... | ... | ... | ... | ... | True |
| ... | | | | | | | | |

### 🧠 Concepts Tested

```
String Cleaning  +  Boolean Filtering  +  GroupBy  +  Named Aggregation  +  GroupBy + Transform (quantile)  +  IQR Computation  +  Boolean Outlier Flag  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- First build the aggregated DataFrame (one row per txn_type + category combination).
- Then, on the **aggregated** DataFrame, use `groupby("txn_type")["total_amount"].transform(...)` to compute Q1 and Q3 — this broadcasts the percentile back to every row in the same txn_type.
- `groupby("txn_type")["total_amount"].transform("quantile", 0.25)` computes Q1 per group. If this syntax is unsupported in your Pandas version, use `.transform(lambda s: s.quantile(0.25))`.
- Compute `iqr = q3 - q1` and `upper_bound = q3 + 1.5 * iqr` as simple column arithmetic.
- `is_outlier = total_amount > upper_bound` creates a boolean column directly.

</details>

---

## ❓ Question 28

---

| | |
|---|---|
| **Question #** | 28 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The Procurement team wants a **Dead Inventory Report** — products that exist in the inventory (`products.csv`) but have **never been successfully delivered** in any order. For each such product, compute the **potential lost revenue** (the revenue the company could have earned if all stock were sold at the listed price). Also include the **vendor name** (cleaned) for context.

### 📝 Problem Statement

1. Clean `products.category`: strip + Title Case
2. From `orders`, get the distinct set of `product_id`s that appear in at least one **Delivered** order
3. Identify **dead inventory products**: products in `products.csv` whose `product_id` does **NOT** appear in the delivered orders set — use `.isin()` with negation
4. For dead inventory products:
   - Keep only rows with non-null `price_inr` AND non-null `stock_quantity`
   - Compute `potential_lost_revenue` = `price_inr` × `stock_quantity`
5. Left join with `vendors` on `vendor_id` to get `vendor_name`
6. Clean `vendor_name`: strip + Title Case
7. Select: `product_id`, `product_name`, `category`, `price_inr`, `stock_quantity`, `potential_lost_revenue`, `vendor_name`
8. Sort by `potential_lost_revenue` descending
9. Reset index

### ✅ Requirements

- Use `isin()` with `~` for the "NOT in delivered" filter
- Use `pd.merge(... how="left")` to bring in vendor names
- All operations must be vectorized Pandas

### 📊 Expected Output Format

| product_id | product_name | category | price_inr | stock_quantity | potential_lost_revenue | vendor_name |
|---|---|---|---|---|---|---|
| P... | ... | Accessories | 1299.0 | 410.0 | 532590.0 | ... |
| ... | | | | | | |

### 🧠 Concepts Tested

```
String Cleaning  +  isin() + Negation (~)  +  Boolean Filtering (nulls)  +  Computed Column  +  Left Merge  +  Column Selection  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `orders[orders["order_status"]=="Delivered"]["product_id"].unique()` gives you the list of delivered product IDs.
- `~products["product_id"].isin(delivered_ids)` filters out products that WERE delivered — leaving only dead inventory.
- After filtering, apply another filter for `notna()` on both `price_inr` and `stock_quantity` before the multiplication.
- The left merge with `vendors` may bring NaN for `vendor_name` if the vendor_id is missing — this is expected.
- Remember to clean `vendor_name` **after** the merge, not before.

</details>

---

## ❓ Question 29

---

| | |
|---|---|
| **Question #** | 29 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The HR team wants a **complete employee tenure report**. For each Active employee, they want to know: how many **full years** they have been with the company (tenure in years), which **tenure bracket** they fall into, and a summary of how many employees are in each bracket **per department**.

### 📝 Problem Statement

From `employees` (Active only, deduplicated by `emp_id`, non-null `hire_date`):

1. Parse `hire_date` as datetime
2. Compute `tenure_years` = number of **complete years** from `hire_date` to **today** (`pd.Timestamp.today()`)
   - Use: `(pd.Timestamp.today() - hire_date).dt.days // 365`
3. Create `tenure_bracket` using `pd.cut()` with these bins and labels:
   - 0–1 years → `"0-1 yr"`
   - 2–3 years → `"2-3 yrs"`
   - 4–6 years → `"4-6 yrs"`
   - 7+ years → `"7+ yrs"`
4. Merge with `departments` (inner join) to get `department_name`
5. Group by `department_name` and `tenure_bracket`, count employees
6. Unstack `tenure_bracket` as columns
7. Fill NaN with `0`, convert to `int`
8. Add `total_headcount` = sum across all bracket columns
9. Sort by `total_headcount` descending

### ✅ Requirements

- Use `pd.Timestamp.today()` — no `datetime` module
- Use `pd.cut()` for binning
- Use `.unstack()` not `pivot_table()`

### 📊 Expected Output Format

| department_name | 0-1 yr | 2-3 yrs | 4-6 yrs | 7+ yrs | total_headcount |
|---|---|---|---|---|---|
| Engineering | ... | ... | ... | ... | ... |
| Sales | ... | ... | ... | ... | ... |
| ... | | | | | |

### 🧠 Concepts Tested

```
Datetime Parsing  +  Timedelta Arithmetic  +  pd.Timestamp.today()  +  pd.cut (Binning)  +  Inner Merge  +  GroupBy  +  unstack  +  fillna + astype  +  Row-wise Sum  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `pd.to_datetime(df["hire_date"])` parses the date strings.
- `(pd.Timestamp.today() - df["hire_date"]).dt.days // 365` computes whole years of tenure.
- `pd.cut(tenure_years, bins=[-1, 1, 3, 6, float("inf")], labels=["0-1 yr","2-3 yrs","4-6 yrs","7+ yrs"])` — note: bins are right-inclusive by default, so `-1` as the lower bound captures 0-year employees.
- After groupby + unstack, remove the column axis name: `df.columns.name = None`.
- The output will vary depending on today's date — that is expected and correct.

</details>

---

## ❓ Question 30

---

| | |
|---|---|
| **Question #** | 30 of 50 |
| **Difficulty** | 🔴 Medium-Hard |
| **Interview Level** | Mid-Level |

### 🏢 Business Scenario

The Operations team wants a **monthly order pipeline report** — a matrix showing, for each month, the **count of orders in each status**, and additionally, the **percentage share** of each status within that month's total. Months with fewer than **5 total orders** should be **excluded**.

### 📝 Problem Statement

From the `orders` DataFrame (all orders, no status filter):

1. Parse `order_date` as datetime; extract `order_month` as `"YYYY-MM"` period string
2. Build a **pivot table**:
   - `index = order_month`
   - `columns = order_status`
   - `values = order_id`
   - `aggfunc = "count"`
3. Fill NaN with `0`, convert to `int`
4. Add `month_total` column = sum of all status columns per row
5. Filter to keep only rows where `month_total >= 5`
6. For each status column, compute a `<status>_pct` column = (status_count / month_total) × 100, rounded to 1 decimal place
7. Sort by `order_month` ascending

### ✅ Requirements

- Use `pd.pivot_table()` with `aggfunc="count"`
- Use `.div(df["month_total"], axis=0)` for vectorized percentage computation across all status columns at once
- The percentage columns should be named `Cancelled_pct`, `Delivered_pct`, etc.
- No loops for creating percentage columns — use `.mul(100).round(1)` on a sub-DataFrame

### 📊 Expected Output Format

| order_month | Cancelled | Delivered | ... | month_total | Cancelled_pct | Delivered_pct | ... |
|---|---|---|---|---|---|---|---|
| 2022-01 | 2 | 5 | ... | 12 | 16.7 | 41.7 | ... |
| ... | | | | | | | |

### 🧠 Concepts Tested

```
Datetime Parsing  +  Period Extraction  +  Pivot Table (count)  +  fillna + astype  +  Row-wise Sum  +  Post-filter  +  Vectorized Percentage Computation (.div axis=0)  +  Column Renaming  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- After building the pivot (count of orders per status per month), add `month_total = df.sum(axis=1)` (before adding percentage columns).
- Filter `month_total >= 5` before computing percentages.
- To compute percentages for all status columns at once: `pct_df = status_cols_df.div(df["month_total"], axis=0).mul(100).round(1)` — where `status_cols_df` is a subset of the DataFrame containing only status columns.
- Rename percentage columns: `pct_df.columns = [c + "_pct" for c in pct_df.columns]`.
- Concatenate the original pivot with the pct DataFrame using `pd.concat([pivot, pct_df], axis=1)`.
- Remove the column axis name for clean output: `df.columns.name = None`.

</details>

---
---

# 🔥 Section 5 — Hard (Questions 31–40)

> These questions require combining 4+ Pandas concepts. Plan your approach before writing a single line of code.

---

## ❓ Question 31

---

| | |
|---|---|
| **Question #** | 31 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The Revenue team wants a **3-month rolling average revenue trend** from Delivered orders to smooth out month-to-month noise. They also want to know how each month's actual revenue compares to its rolling average — the **deviation %** — so they can spot unusually strong or weak months.

### 📝 Problem Statement

From `orders` (Delivered + non-null `amount_inr`):

1. Parse `order_date` as datetime; extract `order_month` as `"YYYY-MM"` period string
2. Group by `order_month`, compute `total_revenue` = sum of `amount_inr`
3. Sort by `order_month` ascending; reset index
4. Compute `rolling_3m_avg` = 3-month rolling mean of `total_revenue` (window=3, min_periods=1)
5. Compute `deviation_pct` = (`total_revenue` − `rolling_3m_avg`) / `rolling_3m_avg` × 100, rounded to 2 dp
6. Compute `prev_month_revenue` = `total_revenue` shifted by 1
7. Compute `mom_change` = `total_revenue` − `prev_month_revenue`
8. Add a `trend` column: `"Up"` if `mom_change > 0`, `"Down"` if `mom_change < 0`, `"Flat"` if `mom_change == 0`, `NaN` for first row
   — Use boolean masking + `pd.Series.where()` or `pd.cut()` logic — no `apply()`
9. Round `total_revenue` and `rolling_3m_avg` to 2 dp

### ✅ Requirements

- Use `.rolling(window=3, min_periods=1).mean()` directly on the Series
- `trend` column must be built without `apply()` — use `pd.Series.where()` chaining or `np`-free masking
- Hint: `pd.cut` on `mom_change` with bins `[-inf, 0, 0, inf]` won't work for exact zero; use masking instead

### 📊 Expected Output Format

| order_month | total_revenue | rolling_3m_avg | deviation_pct | prev_month_revenue | mom_change | trend |
|---|---|---|---|---|---|---|
| 2022-01 | ... | ... | ... | NaN | NaN | NaN |
| 2022-02 | ... | ... | +8.3 | ... | ... | Up |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Datetime + Period  +  GroupBy  +  Sorting  +  rolling().mean()  +  shift()  +  Arithmetic  +  Conditional Column (masking without apply)
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- After groupby and sort, your result is a clean monthly Series — call `.rolling(3, min_periods=1).mean()` directly on `total_revenue`.
- `shift(1)` gives the previous month's revenue. Compute `mom_change = total_revenue - prev_month_revenue`.
- For the `trend` column without `apply()`: start with a Series of NaN, then use boolean masking:
  `trend = pd.Series("Flat", index=result.index)` then overwrite with `.where(mom_change <= 0, "Up")` etc.
  Or chain: `trend = result["mom_change"].gt(0).map({True:"Up",False:None})` — experiment.
- `deviation_pct` may be 0.0 for the first row since `rolling_3m_avg` = `total_revenue` when `min_periods=1` and only 1 value.

</details>

---

## ❓ Question 32

---

| | |
|---|---|
| **Question #** | 32 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The Growth team wants a **Pareto (80/20) analysis** of customer revenue. They want to know: what percentage of customers account for **80% of total Delivered revenue**? The output should show the cumulative revenue table so leadership can see the concentration clearly.

### 📝 Problem Statement

From `orders` (Delivered + non-null `amount_inr`):

1. Group by `customer_id`, compute `total_spend` = sum of `amount_inr`
2. Sort by `total_spend` **descending**; reset index
3. Compute `cumulative_revenue` = cumulative sum of `total_spend`
4. Compute `cumulative_revenue_pct` = `cumulative_revenue` / total revenue × 100, rounded to 2 dp
5. Compute `customer_rank` = row number (1-indexed) — the top spender is rank 1
6. Compute `customer_pct` = `customer_rank` / total distinct customers × 100, rounded to 2 dp
7. Add a boolean column `within_pareto_80` = True where `cumulative_revenue_pct <= 80`
8. Keep all rows in the output
9. At the end, **print** a summary:
   - How many customers (count + %) account for the top 80% of revenue
   - What is the revenue threshold at the 80% boundary

### ✅ Requirements

- No loops — use `cumsum()`, arithmetic, and boolean masking entirely
- `customer_rank` = use `reset_index()` after sort, then `index + 1`

### 📊 Expected Output Format

| customer_id | total_spend | cumulative_revenue | cumulative_revenue_pct | customer_rank | customer_pct | within_pareto_80 |
|---|---|---|---|---|---|---|
| C... | ... | ... | 5.32 | 1 | 1.85 | True |
| C... | ... | ... | 10.1 | 2 | 3.70 | True |
| ... | | | | | | |

`→ X customers (Y%) account for 80% of revenue. Revenue threshold: ₹Z`

### 🧠 Concepts Tested

```
Boolean Filtering  +  GroupBy  +  Sorting  +  cumsum()  +  Arithmetic (cumulative %)  +  reset_index (rank)  +  Boolean Column  +  Scalar Summary Output
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- After `groupby("customer_id").agg(total_spend=("amount_inr","sum"))`, sort descending and reset index.
- `result["cumulative_revenue"] = result["total_spend"].cumsum()`
- Total revenue = `result["total_spend"].sum()` — compute this scalar before building the percentage column.
- `customer_rank = result.index + 1` after `reset_index(drop=True)` gives 1-based ranks.
- `total_customers = len(result)` — use this for `customer_pct`.
- For the summary: `pareto_df = result[result["within_pareto_80"]]` — then `len(pareto_df)` and `pareto_df["total_spend"].min()` gives the threshold.

</details>

---

## ❓ Question 33

---

| | |
|---|---|
| **Question #** | 33 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The Customer Success team wants a **Customer Cohort Revenue Report**. Customers are grouped into cohorts by the **year they joined** (from `customers.csv`). For each cohort, the team wants: total customers, total lifetime revenue from Delivered orders, average revenue per customer, the revenue of the single best customer in that cohort, and a rank of cohorts by average revenue per customer.

### 📝 Problem Statement

1. Parse `customers.join_date` as datetime; extract `cohort_year` = `.dt.year`
2. Deduplicate `customers` on `customer_id` (keep first); clean `customer_name` (strip + title)
3. Clean `customers.segment` (strip + title)
4. Merge deduplicated customers with `orders` (Delivered + non-null `amount_inr`) on `customer_id` using a **left join from customers** (so customers with 0 orders are retained)
5. Group by `cohort_year` and compute:
   - `total_customers` — `nunique("customer_id")`
   - `total_revenue` — sum of `amount_inr`, with `NaN` treated as 0 using `fillna(0)` before grouping
   - `avg_revenue_per_customer` — `total_revenue / total_customers`, rounded to 2 dp
   - `best_customer_revenue` — max `amount_inr` per group (NaN → 0)
6. Add `cohort_rank` = dense rank of `avg_revenue_per_customer` descending (as int)
7. Sort by `cohort_rank` ascending
8. Reset index

### ✅ Requirements

- Left join keeps customers with no orders; their `amount_inr` will be NaN — fill with 0
- `avg_revenue_per_customer` is a **derived column** computed after aggregation, not directly from `agg()`
- Use `rank(method="dense", ascending=False)` on the result DataFrame

### 📊 Expected Output Format

| cohort_year | total_customers | total_revenue | avg_revenue_per_customer | best_customer_revenue | cohort_rank |
|---|---|---|---|---|---|
| 2020 | ... | ... | ... | ... | 1 |
| 2019 | ... | ... | ... | ... | 2 |
| ... | | | | | |

### 🧠 Concepts Tested

```
Datetime Parsing  +  Cohort Extraction  +  Deduplication  +  String Cleaning  +  Left Merge  +  fillna  +  GroupBy + Named Aggregation  +  Derived Column Arithmetic  +  rank()  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- The join direction matters: `pd.merge(customers_dedup, orders_filtered, on="customer_id", how="left")` — customers is on the left so all customers appear even without orders.
- After the merge, fill `amount_inr` nulls with 0 **before** grouping: `merged["amount_inr"].fillna(0, inplace=True)` or reassign.
- For `total_customers`, use `nunique("customer_id")` inside `agg()` — each cohort's unique customer count.
- `avg_revenue_per_customer` cannot be computed directly in `agg()` because it depends on two aggregated values. Compute it after: `result["total_revenue"] / result["total_customers"]`.
- `rank(method="dense", ascending=False).astype(int)` on the result column gives clean integer ranks.

</details>

---

## ❓ Question 34

---

| | |
|---|---|
| **Question #** | 34 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The HR team wants to identify employees who are in the **top 25% salary earners within their department + city group**. This is more granular than a simple dept-level analysis — it accounts for cost-of-living differences by city. The output should show each qualifying employee's salary percentile within their group, enriched with the department name.

### 📝 Problem Statement

From `employees` (Active only, deduplicated by `emp_id`, non-null salary):

1. Deduplicate by `emp_id` (keep first); filter Active + non-null salary
2. Compute `salary_pct_rank` = salary percentile within each `dept_id + city` group
   - Use `groupby(["dept_id","city"])["salary_inr"].rank(pct=True)` — this gives values from 0 to 1
   - Multiply by 100 and round to 1 dp to get percentile (0–100)
3. Filter to keep only employees with `salary_pct_rank >= 75` (top quartile within their group)
4. Merge with `departments` (inner join) to get `department_name` and `manager_name`
5. Select: `emp_id`, `employee_name`, `department_name`, `city`, `salary_inr`, `salary_pct_rank`, `manager_name`
6. Sort by `department_name` ASC, `salary_pct_rank` DESC
7. Reset index

### ✅ Requirements

- Use `groupby().rank(pct=True)` — Pandas native percentile rank
- Groups with only 1 employee will have `salary_pct_rank = 100.0` (sole member = top of group)
- No loops, no `apply()`

### 📊 Expected Output Format

| emp_id | employee_name | department_name | city | salary_inr | salary_pct_rank | manager_name |
|---|---|---|---|---|---|---|
| E... | ... | Engineering | Bengaluru | 112000.0 | 100.0 | ... |
| E... | ... | Finance | Mumbai | 95000.0 | 87.5 | ... |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Deduplication  +  Boolean Filtering  +  GroupBy + rank(pct=True)  +  Percentile Arithmetic  +  Boolean Filter (top quartile)  +  Inner Merge  +  Column Selection  +  Multi-column Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `groupby(["dept_id","city"])["salary_inr"].rank(pct=True)` returns values in [0, 1]. Multiply by 100 to convert to percentile scale (0–100).
- Assign this as a new column **before** filtering.
- Filter `salary_pct_rank >= 75` to keep the top quartile.
- The inner join with `departments` will drop employees whose `dept_id` doesn't exist in departments — this is intentional (those without a valid dept are excluded from the report).
- A solo employee in a dept+city group will always have percentile rank = 100.0 (they are the highest by default).

</details>

---

## ❓ Question 35

---

| | |
|---|---|
| **Question #** | 35 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The Supply Chain Director wants a **Vendor Performance Scorecard** — a single ranked table where vendors are evaluated on two dimensions: revenue generated and product diversity. The composite rank is the sum of their individual ranks on each dimension (lower composite = better overall performer).

### 📝 Problem Statement

1. Filter `orders` to Delivered + non-null `amount_inr`
2. Merge orders → `products` (inner join on `product_id`)
3. Clean `vendors.vendor_name`: strip + Title Case
4. Merge → `vendors` (inner join on `vendor_id`)
5. Group by `vendor_id` + `vendor_name`, compute:
   - `total_revenue` — sum of `amount_inr`, rounded to 2 dp
   - `unique_products_sold` — `nunique("product_id")`
   - `unique_categories` — `nunique` of **cleaned** `category` (strip + title on products.category first)
   - `total_orders` — count of orders
6. Reset index
7. Compute:
   - `revenue_rank` — dense rank of `total_revenue` ascending (rank 1 = lowest revenue = worst)
   - `diversity_rank` — dense rank of `unique_products_sold` ascending
   - `composite_score` = `revenue_rank` + `diversity_rank`
8. Sort by `composite_score` ascending (rank 1 composite = best overall performer)
9. Reset index (drop=True)

### ✅ Requirements

- Clean `products.category` **before** the merge or after — but before the `nunique` groupby
- `revenue_rank` and `diversity_rank` use `rank(method="dense", ascending=True)` on the result DataFrame
- `composite_score` is a simple arithmetic column

### 📊 Expected Output Format

| vendor_id | vendor_name | total_revenue | unique_products_sold | unique_categories | total_orders | revenue_rank | diversity_rank | composite_score |
|---|---|---|---|---|---|---|---|---|
| V007 | Mobilezone | ... | ... | ... | ... | 7 | 6 | 13 |
| V003 | Storagepro Inc | ... | ... | ... | ... | 4 | 3 | 7 |
| ... | | | | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Two Sequential Merges  +  String Cleaning (two columns)  +  GroupBy + Multiple Aggregations (sum, nunique×2, count)  +  rank() on Result DataFrame  +  Composite Score Arithmetic  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Clean `products.category` and `vendors.vendor_name` **before** the merges.
- After both merges, group by `["vendor_id","vendor_name"]` and use named aggregation.
- For `unique_categories`, make sure you're calling `nunique()` on the cleaned category column of the merged DataFrame.
- Ranks are computed on the **aggregated result DataFrame**: `result["revenue_rank"] = result["total_revenue"].rank(method="dense", ascending=True).astype(int)`
- `ascending=True` means the vendor with the **lowest revenue gets rank 1** — the worst performer. The composite score then naturally identifies the vendor that scores highest on both dimensions when sorted ascending.

</details>

---

## ❓ Question 36

---

| | |
|---|---|
| **Question #** | 36 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The Internal Audit team wants a **Data Reconciliation Report** for the orders dataset — a single summary table identifying three distinct data integrity issues:
- **Issue A** — Orders whose `product_id` does not exist in `products.csv` (orphan orders)
- **Issue B** — Orders whose `customer_id` does not exist in `customers.csv` (ghost customers)
- **Issue C** — Orders marked as `Delivered` but with a **null** `amount_inr` (billing failure)

### 📝 Problem Statement

From the `orders` DataFrame:

1. Deduplicate `customers` by `customer_id` (keep first)
2. Identify:
   - **Issue A** rows: `~orders["product_id"].isin(products["product_id"])`
   - **Issue B** rows: `~orders["customer_id"].isin(customers_dedup["customer_id"])`
   - **Issue C** rows: `(orders["order_status"] == "Delivered") & (orders["amount_inr"].isna())`
3. For each issue, compute:
   - `affected_orders` — count of orders with this issue
   - `pct_of_total` — percentage of total orders, rounded to 2 dp
   - `total_amount_affected` — sum of `amount_inr` for affected rows (NaN → 0 using `fillna`)
4. Build a **summary DataFrame** with columns: `issue`, `description`, `affected_orders`, `pct_of_total`, `total_amount_affected`
   - Use `pd.DataFrame([row_a, row_b, row_c])` — three rows, one per issue
5. Sort by `affected_orders` descending

### ✅ Requirements

- Use `isin()` with `~` for orphan/ghost detection
- Build the summary using `pd.DataFrame([...])` with dicts — no loops on rows
- Treat the three issue detections as three separate filtering operations

### 📊 Expected Output Format

| issue | description | affected_orders | pct_of_total | total_amount_affected |
|---|---|---|---|---|
| Issue B | Ghost customers | ... | ...% | ... |
| Issue A | Orphan orders | ... | ...% | ... |
| Issue C | Delivered + null amount | ... | ...% | 0.0 |

### 🧠 Concepts Tested

```
Deduplication  +  isin() + Negation (~)  +  Multiple Boolean Conditions  +  fillna  +  Scalar Aggregation (count, sum, %)  +  pd.DataFrame construction from dicts  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `total_orders = len(orders)` — compute this once as a scalar.
- For each issue, filter the orders DataFrame, then compute `len(filtered)`, `len(filtered) / total_orders * 100`, and `filtered["amount_inr"].fillna(0).sum()`.
- Build each row as a Python dict: `{"issue": "Issue A", "description": "...", ...}`.
- `pd.DataFrame([dict_a, dict_b, dict_c])` creates the summary — this is NOT a loop over rows; it's a one-shot construction.
- Issue C rows will always have `total_amount_affected = 0` since `amount_inr` is null by definition — `fillna(0).sum() = 0`.

</details>

---

## ❓ Question 37

---

| | |
|---|---|
| **Question #** | 37 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The CRM team wants to identify the **Top 1 spending customer per city per order month**. They need a monthly leaderboard — for each city and month combination, which customer spent the most (across all their Delivered orders in that month), what was their total spend, and how many orders did they place?

### 📝 Problem Statement

From `orders` (Delivered + non-null `amount_inr`) merged with deduplicated, cleaned `customers`:

1. Deduplicate `customers` by `customer_id` (keep first); clean `customer_name` (strip + title)
2. Parse `orders.order_date` as datetime; extract `order_month` as `"YYYY-MM"` period string
3. Merge filtered orders with deduplicated customers on `customer_id` (inner join)
4. Group by `city`, `order_month`, `customer_id`, `customer_name`, compute:
   - `monthly_spend` — sum of `amount_inr`
   - `order_count` — count of orders
5. Within each `city + order_month` group, **dense rank** customers by `monthly_spend` descending
   - Store as `city_month_rank`
6. Filter to keep only `city_month_rank == 1`
7. Select: `city`, `order_month`, `customer_id`, `customer_name`, `monthly_spend`, `order_count`
8. Sort by `order_month` ASC, `city` ASC
9. Reset index

### ✅ Requirements

- If two customers tie for top spend in the same city+month, both should appear (dense rank = 1 for both)
- Use `groupby(["city","order_month"])["monthly_spend"].rank(method="dense", ascending=False)`

### 📊 Expected Output Format

| city | order_month | customer_id | customer_name | monthly_spend | order_count |
|---|---|---|---|---|---|
| Bengaluru | 2022-01 | C... | ... | ... | ... |
| Bengaluru | 2022-02 | C... | ... | ... | ... |
| Delhi | 2022-01 | C... | ... | ... | ... |
| ... | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Deduplication  +  String Cleaning  +  Datetime + Period  +  Inner Merge  +  Multi-key GroupBy Aggregation  +  GroupBy + Dense Rank (2-level group)  +  Filter  +  Multi-column Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- The groupby has 4 keys: `["city","order_month","customer_id","customer_name"]` — this gives one row per customer per city per month.
- After aggregation, reset the index so all four keys become regular columns.
- The ranking groupby has only 2 keys: `["city","order_month"]` — rank within this narrower group.
- `groupby(["city","order_month"])["monthly_spend"].rank(method="dense", ascending=False)` returns a float Series aligned to the aggregated DataFrame. Assign as `city_month_rank`.
- Convert `city_month_rank` to int before filtering.
- Dense rank means ties both get rank 1 — which is intentional here.

</details>

---

## ❓ Question 38

---

| | |
|---|---|
| **Question #** | 38 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The Workforce Planning team wants a **Department Budget Overspend Report**. For each department, compute the **total active salary cost** and compare it to the department's allocated budget. Flag departments where salary cost exceeds **70%** of budget as "At Risk", and departments where it exceeds **90%** as "Critical".

### 📝 Problem Statement

1. Deduplicate `employees` by `emp_id` (keep first); filter Active + non-null salary
2. Merge with `departments` on `dept_id` (inner join) to get `department_name` and `budget_inr`
3. Group by `dept_id`, `department_name`, `budget_inr`, compute:
   - `total_salary_cost` — sum of `salary_inr`
   - `headcount` — count of employees
   - `avg_salary` — mean of `salary_inr`, rounded to 2 dp
4. Compute:
   - `budget_utilization_pct` = (`total_salary_cost` / `budget_inr`) × 100, rounded to 2 dp
   - `remaining_budget` = `budget_inr` − `total_salary_cost`
   - `budget_status`: `"Critical"` if `budget_utilization_pct > 90`, `"At Risk"` if `> 70`, `"Healthy"` otherwise
     — Build using boolean masking with `pd.Series.where()` — no `apply()`
5. Sort by `budget_utilization_pct` descending
6. Reset index

### ✅ Requirements

- `budget_utilization_pct` and `budget_status` are computed **after** aggregation
- `budget_status` must be a vectorized operation — chain `.where()` or use boolean masking
- No `apply()`, no loops

### 📊 Expected Output Format

| dept_id | department_name | budget_inr | total_salary_cost | headcount | avg_salary | budget_utilization_pct | remaining_budget | budget_status |
|---|---|---|---|---|---|---|---|---|
| D07 | ... | 5000000 | ... | ... | ... | 15.xx | ... | Healthy |
| D05 | ... | 6000000 | ... | ... | ... | 12.xx | ... | Healthy |
| ... | | | | | | | | |

### 🧠 Concepts Tested

```
Deduplication  +  Boolean Filtering  +  Inner Merge  +  GroupBy (3-key)  +  Named Aggregation  +  Post-Aggregation Arithmetic  +  Multi-condition String Column (where chaining)  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Grouping by `["dept_id","department_name","budget_inr"]` keeps the budget column accessible after groupby — since all employees in a dept share the same budget, this is safe.
- After computing `budget_utilization_pct`, build `budget_status` using chained `.where()`:
  `status = pd.Series("Healthy", index=result.index)`
  `status = status.where(result["budget_utilization_pct"] <= 70, "At Risk")`
  `status = status.where(result["budget_utilization_pct"] <= 90, "Critical")`
- Apply conditions from least to most severe — the second `.where()` overwrites "At Risk" with "Critical" where needed.
- `remaining_budget = budget_inr - total_salary_cost` is straightforward column arithmetic.

</details>

---

## ❓ Question 39

---

| | |
|---|---|
| **Question #** | 39 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The Finance Controller wants a **Per-Employee Net Transaction Position Report** for H1 2024. For each Active employee who appears in the transactions dataset, compute their **total credit amount** and **total debit amount** from Successful transactions in H1 2024, their **net position** (credit − debit), and flag employees with a **negative net position** (they spent more than they received). Enrich with department name and sort worst-to-best.

### 📝 Problem Statement

1. Filter `transactions` to `txn_status == "Success"` and `amount_inr` not null
2. Parse `txn_date` as datetime; filter to H1 2024 (Jan–Jun 2024: `dt.year == 2024` and `dt.month <= 6`)
3. Group by `emp_id` and `txn_type`, compute `total_amount` = sum of `amount_inr`
4. **Unstack** `txn_type` as columns; fill NaN with 0
   - You should now have columns: `Credit`, `Debit`, `Refund`, `Transfer` (or whichever types exist)
5. Flatten column names if needed; reset index
6. Compute:
   - `net_position` = `Credit` − `Debit` (if those columns exist; handle missing columns with `.get()` or `reindex`)
   - `is_negative` = True where `net_position < 0`
7. Merge with `employees` (Active + deduplicated) on `emp_id` (inner join) to get `employee_name`, `dept_id`
8. Merge with `departments` on `dept_id` (inner join) to get `department_name`
9. Select: `emp_id`, `employee_name`, `department_name`, `Credit`, `Debit`, `net_position`, `is_negative`
10. Round all amount columns to 2 dp
11. Sort by `net_position` ascending (worst net position first)
12. Reset index

### ✅ Requirements

- Use `.unstack()` to pivot txn_type — not `pivot_table()`
- Use `reindex(columns=[...], fill_value=0)` to guarantee all expected txn_type columns exist
- Two sequential inner merges (transactions → employees → departments)

### 📊 Expected Output Format

| emp_id | employee_name | department_name | Credit | Debit | net_position | is_negative |
|---|---|---|---|---|---|---|
| E... | ... | Finance | 12500.0 | 45000.0 | −32500.0 | True |
| E... | ... | Engineering | 8000.0 | 30000.0 | −22000.0 | True |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Datetime (year + month filter)  +  GroupBy  +  unstack  +  fillna + reindex  +  Computed Columns (net, boolean)  +  Two Sequential Inner Merges  +  Column Selection  +  round()  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- H1 2024 filter: `(dt.year == 2024) & (dt.month <= 6)` — combine with `&`.
- After `groupby(["emp_id","txn_type"]).agg(...)`, you have a multi-index Series or DataFrame. Call `.unstack("txn_type")` to reshape — this pivots txn_type into columns.
- `.fillna(0)` after unstack handles missing transaction types for some employees.
- Use `df.reindex(columns=["Credit","Debit","Refund","Transfer"], fill_value=0)` to ensure all columns exist even if some txn_types had no data in H1 2024.
- After the unstack, column names may be a MultiIndex — flatten with `df.columns = df.columns.get_level_values(-1)` or `["_".join(c).strip() for c in df.columns]`.
- `net_position = df["Credit"] - df["Debit"]` — straightforward once columns are flat.

</details>

---

## ❓ Question 40

---

| | |
|---|---|
| **Question #** | 40 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Data Engineer |

### 🏢 Business Scenario

The People Analytics team wants to identify **high-potential employees** using a composite filter. An employee qualifies as high-potential if **all three** of the following conditions are true:
- ✅ Their salary is **at or above the median salary** of their department
- ✅ Their **average H1 2024 attendance rate** is **≥ 90%**
- ✅ They have been with the company for **≥ 3 years** (tenure)

### 📝 Problem Statement

1. Start with `employees` — Active only, deduplicated by `emp_id`, non-null salary and hire_date
2. Parse `hire_date`; compute `tenure_years` = `(pd.Timestamp.today() - hire_date).dt.days // 365`
3. Compute `dept_median_salary` per employee using `groupby("dept_id")["salary_inr"].transform("median")`
4. Add boolean `above_median` = `salary_inr >= dept_median_salary`
5. From `attendance`: parse `month`, filter H1 2024 (year=2024, month≤6), drop null `present_days`
   - Compute `attendance_rate` per row = `(present_days / working_days) * 100`
   - Group by `emp_id`, compute `avg_attendance_h1` = mean of `attendance_rate`, rounded to 2 dp
6. Merge employees with attendance summary on `emp_id` (left join — keep all Active employees; those with no attendance record get NaN → exclude with `dropna`)
7. Apply all three filters simultaneously:
   - `above_median == True`
   - `avg_attendance_h1 >= 90`
   - `tenure_years >= 3`
8. Merge with `departments` (inner join) to get `department_name`
9. Select: `emp_id`, `employee_name`, `department_name`, `salary_inr`, `dept_median_salary`, `avg_attendance_h1`, `tenure_years`
10. Sort by `department_name` ASC, `salary_inr` DESC
11. Reset index

### ✅ Requirements

- Use `groupby().transform("median")` for dept median — NOT `agg()`
- All three conditions must be applied as a single compound boolean mask
- No loops, no `apply()`

### 📊 Expected Output Format

| emp_id | employee_name | department_name | salary_inr | dept_median_salary | avg_attendance_h1 | tenure_years |
|---|---|---|---|---|---|---|
| E... | ... | Data Science | 112000.0 | 88000.0 | 93.18 | 7 |
| E... | ... | Engineering | 100000.0 | 85000.0 | 91.67 | 5 |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Deduplication  +  Boolean Filtering  +  Datetime + Timedelta Tenure  +  GroupBy + Transform (median)  +  Attendance Pipeline (parse→filter→compute→group)  +  Left Merge + dropna  +  Multi-condition Compound Filter  +  Inner Merge  +  Column Selection  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- This question requires building **two independent pipelines** and then merging them:
  - **Pipeline 1**: employees (dedup + filter + tenure + dept_median)
  - **Pipeline 2**: attendance (filter H1 2024 + compute rate + groupby avg)
- `transform("median")` broadcasts the department median salary to every employee row — this is the key difference from `agg("median")` which would collapse the group.
- Left join with attendance summary: employees with no attendance data get `NaN` for `avg_attendance_h1`. Use `dropna(subset=["avg_attendance_h1"])` to remove them before filtering.
- The three conditions compound filter: `mask = above_median & (avg_attendance_h1 >= 90) & (tenure_years >= 3)`. All three must be True simultaneously.
- Round `dept_median_salary` to 2 dp after the transform for clean output.

</details>

---
---

# 🔥 Section 6 — Hard: Final Batch (Questions 41–50)

> **The final 10.** Each question requires 5+ Pandas concepts working in concert. These simulate real Senior/Lead-level interview problems. Think before you type.

---

## ❓ Question 41

---

| | |
|---|---|
| **Question #** | 41 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The Growth team wants a classic **Customer Cohort Retention Analysis**. Customers are grouped into cohorts by the **month they joined** (`customers.join_date`). For each cohort, track how many distinct customers placed at least one Delivered order in each of the **first 6 months** after joining (Month 0 = same month as join, Month 1 = 1 month later, etc.). The output is a **cohort retention matrix** (rows = cohort, columns = Month 0–5, values = customer count).

### 📝 Problem Statement

1. Deduplicate `customers` by `customer_id` (keep first); parse `join_date`; extract `cohort_month` = period `"YYYY-MM"`
2. Filter `orders` to Delivered + non-null `amount_inr`; parse `order_date`; extract `order_month` = period `"YYYY-MM"`
3. Merge orders with customers on `customer_id` (inner join)
4. Compute `months_since_join` = number of months between `order_month` and `cohort_month`
   - Use: `(order_month.dt.to_timestamp() - cohort_month.dt.to_timestamp()).dt.days // 30`
   - Or: convert both to period ordinal and subtract: `order_month.dt.to_timestamp().dt.to_period("M").view("int64") - cohort_month.dt.to_timestamp().dt.to_period("M").view("int64")`
   - Keep only `months_since_join` in range 0–5
5. Group by `cohort_month` and `months_since_join`, count **distinct** `customer_id`s
6. Unstack `months_since_join` as columns; fill NaN with 0; convert to int
7. Rename columns to `Month_0`, `Month_1`, ..., `Month_5`
8. Sort by `cohort_month` ascending

### ✅ Requirements

- Use `pd.Period` arithmetic or `.dt.to_timestamp()` for month difference — no Python `datetime` module
- Use `nunique("customer_id")` for counting distinct customers per cell
- Use `.unstack()` — no `pivot_table()`

### 📊 Expected Output Format

| cohort_month | Month_0 | Month_1 | Month_2 | Month_3 | Month_4 | Month_5 |
|---|---|---|---|---|---|---|
| 2019-03 | 4 | 2 | 3 | 1 | 2 | 0 |
| 2019-04 | 2 | 1 | 1 | 2 | 1 | 1 |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Deduplication  +  Datetime Parsing × 2  +  Period Extraction  +  Inner Merge  +  Period Arithmetic (months_since_join)  +  Boolean Filtering (0–5)  +  GroupBy + nunique  +  unstack  +  fillna + astype  +  Column Renaming  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Convert both period columns to timestamps, then subtract and divide days by 30 for approximate month difference.
- A cleaner approach: `.dt.to_period("M")` produces Period objects. Subtract them directly: `merged["order_month"] - merged["cohort_month"]` — this gives an integer number of months (as a `DateOffset`). Use `.n` attribute or convert both to ordinals: `order_period.view("int64") - cohort_period.view("int64")`.
- Filter `months_since_join.between(0, 5)` to keep only the first 6 months.
- `groupby(["cohort_month","months_since_join"])["customer_id"].nunique()` gives the retention counts.
- After `.unstack()`, rename columns: `df.columns = [f"Month_{c}" for c in df.columns]`.

</details>

---

## ❓ Question 42

---

| | |
|---|---|
| **Question #** | 42 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The Merchandising team wants to discover **product cross-sell pairs** — pairs of products that are frequently purchased by the **same customer on the same order date**. This is a market basket-style analysis, done entirely in Pandas using a **self-join**.

### 📝 Problem Statement

From `orders` (Delivered + non-null `product_id` + non-null `amount_inr`):

1. Filter and select only `customer_id`, `product_id`, `order_date` columns
2. Parse `order_date` as datetime; keep date only (`.dt.date` → convert back to datetime)
3. Drop duplicate `(customer_id, product_id, order_date)` combinations (a customer buying the same product twice on same day should count once)
4. **Self-join**: merge this DataFrame with itself on `["customer_id","order_date"]` (inner join)
   - This gives you all product pairs bought by the same customer on the same date
   - Rename columns: left side → `product_a`, right side → `product_b` (using suffixes)
5. Remove self-pairs: filter out rows where `product_a == product_b`
6. Remove duplicate reversed pairs: keep only rows where `product_a < product_b` (string comparison)
7. Group by `product_a` and `product_b`, count `customer_id` (= co-purchase frequency)
8. Merge with `products` twice to get product names:
   - Once for `product_a` to get `product_a_name`
   - Once for `product_b` to get `product_b_name`
9. Sort by `co_purchase_count` descending; show top 20 pairs
10. Select: `product_a`, `product_a_name`, `product_b`, `product_b_name`, `co_purchase_count`

### ✅ Requirements

- The self-join must use `pd.merge(df, df, on=[...])` — two references to the same DataFrame
- `product_a < product_b` ensures each pair appears only once (deduplication of A-B vs B-A)
- No loops, no `itertools`

### 📊 Expected Output Format

| product_a | product_a_name | product_b | product_b_name | co_purchase_count |
|---|---|---|---|---|
| P003 | ... | P011 | ... | 8 |
| P007 | ... | P019 | ... | 6 |
| ... | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  drop_duplicates (3-column key)  +  Self-Join (merge with itself)  +  Suffix Rename  +  Self-Pair Removal  +  Symmetric Pair Deduplication (< comparison)  +  GroupBy  +  Two Lookup Merges  +  Sorting + head()
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `pd.merge(df, df, on=["customer_id","order_date"], suffixes=("_a","_b"))` — both sides are the same DataFrame object. Pandas handles this correctly.
- After the self-join, you have `product_id_a` and `product_id_b` columns.
- Filter `product_id_a != product_id_b` first (remove self-pairs).
- Then filter `product_id_a < product_id_b` — string comparison works fine for IDs like "P003" < "P011".
- Group by `["product_id_a","product_id_b"]` and count `customer_id` occurrences.
- Merge with `products[["product_id","product_name"]]` twice: once for `_a`, once for `_b`, using `left_on`/`right_on`.

</details>

---

## ❓ Question 43

---

| | |
|---|---|
| **Question #** | 43 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The HR Compensation team wants a **Salary Z-Score Audit** per department. For each Active employee, compute how many standard deviations their salary deviates from their department's mean salary. Employees with a **Z-score beyond ±2.0** are flagged as statistical outliers — either dramatically overpaid or underpaid relative to peers.

### 📝 Problem Statement

From `employees` (Active, deduplicated by `emp_id`, non-null salary):

1. Deduplicate; filter Active + non-null salary
2. Compute per-dept statistics using `transform`:
   - `dept_mean_salary` = `groupby("dept_id")["salary_inr"].transform("mean")`
   - `dept_std_salary` = `groupby("dept_id")["salary_inr"].transform("std")`
3. Compute `z_score` = (`salary_inr` − `dept_mean_salary`) / `dept_std_salary`, rounded to 3 dp
   - Departments with only 1 employee will have `std = NaN` → `z_score = NaN` — leave as NaN
4. Add `outlier_direction`: `"Overpaid"` if `z_score > 2`, `"Underpaid"` if `z_score < -2`, `"Normal"` otherwise, `NaN` if z_score is NaN
   - Use `pd.Series.where()` chaining — no `apply()`
5. Merge with `departments` (inner join) to get `department_name`
6. Filter to keep only outliers: `|z_score| > 2` (i.e., `z_score > 2` or `z_score < -2`)
7. Select: `emp_id`, `employee_name`, `department_name`, `city`, `salary_inr`, `dept_mean_salary`, `dept_std_salary`, `z_score`, `outlier_direction`
8. Round `dept_mean_salary` and `dept_std_salary` to 2 dp
9. Sort by `z_score` — most extreme first (sort by `z_score.abs()` descending)
10. Reset index

### ✅ Requirements

- Use `transform("mean")` and `transform("std")` — not `agg()`
- `outlier_direction` built via chained `.where()` — no `apply()`
- Sort by **absolute value** of z_score descending — use `.abs()` for the sort key

### 📊 Expected Output Format

| emp_id | employee_name | department_name | city | salary_inr | dept_mean_salary | dept_std_salary | z_score | outlier_direction |
|---|---|---|---|---|---|---|---|---|
| E... | ... | Engineering | Pune | 148000 | 92000 | 18500 | 3.027 | Overpaid |
| E... | ... | Sales | Delhi | 42000 | 78000 | 15000 | −2.400 | Underpaid |
| ... | | | | | | | | |

### 🧠 Concepts Tested

```
Deduplication  +  Boolean Filtering  +  GroupBy + Transform (mean + std)  +  Z-Score Arithmetic  +  Conditional Column (where chaining)  +  Inner Merge  +  abs()-based Sorting  +  round() × multiple
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `transform("std")` uses the sample standard deviation (ddof=1) by default — correct for Z-score.
- When a dept has only 1 employee, `std = NaN`, so `z_score = NaN`. These employees will be excluded by the `|z_score| > 2` filter automatically.
- Build `outlier_direction`:
  `direction = pd.Series("Normal", index=df.index)`
  `direction = direction.where(df["z_score"] <= 2, "Overpaid")`  # z > 2 → "Overpaid"
  `direction = direction.where(df["z_score"] >= -2, "Underpaid")`  # z < -2 → "Underpaid"
  `direction = direction.where(df["z_score"].notna(), pd.NA)  # NaN z → NaN direction`
- To sort by absolute z_score: `result.sort_values(by="z_score", key=lambda s: s.abs(), ascending=False)`.

</details>

---

## ❓ Question 44

---

| | |
|---|---|
| **Question #** | 44 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The CRM team wants to **segment customers by Lifetime Value (CLV)** using the **RFM framework** (Recency, Frequency, Monetary). Using Delivered orders:
- **Recency** = days since the customer's most recent order (vs today)
- **Frequency** = total number of Delivered orders
- **Monetary** = total spend from Delivered orders

After computing RFM, segment customers into 4 tiers using `pd.qcut` on each metric, then compute a composite RFM score to assign a final segment label.

### 📝 Problem Statement

From `orders` (Delivered + non-null `amount_inr`):

1. Parse `order_date` as datetime
2. Group by `customer_id`, compute:
   - `recency_days` = (`pd.Timestamp.today()` − max `order_date`).days
   - `frequency` = count of orders
   - `monetary` = sum of `amount_inr`, rounded to 2 dp
3. Reset index
4. Compute RFM scores (1–4 scale) using `pd.qcut` with `labels=[4,3,2,1]` for Recency (lower recency days = better → higher score = quartile 1), and `labels=[1,2,3,4]` for Frequency and Monetary (higher = better):
   - `r_score` = `pd.qcut(recency_days, q=4, labels=[4,3,2,1])`.astype(int)
   - `f_score` = `pd.qcut(frequency, q=4, labels=[1,2,3,4], duplicates="drop")`.astype(int)
   - `m_score` = `pd.qcut(monetary, q=4, labels=[1,2,3,4])`.astype(int)
5. Compute `rfm_score` = `r_score` + `f_score` + `m_score`
6. Assign `segment` using `pd.cut` on `rfm_score`:
   - 10–12 → `"Platinum"`
   - 7–9 → `"Gold"`
   - 4–6 → `"Silver"`
   - 3 → `"Bronze"`
7. Group by `segment`, compute: `customer_count`, `avg_monetary` (mean, rounded to 2 dp), `avg_frequency` (mean, rounded to 1 dp)
8. Sort by `rfm_score` range (Platinum → Gold → Silver → Bronze) — use `pd.Categorical` with ordered categories

### ✅ Requirements

- Use `pd.qcut()` for RFM scoring — not `pd.cut()`
- Use `pd.cut()` for the final segment assignment
- Use `pd.Categorical` for ordered segment sorting

### 📊 Expected Output Format

| segment | customer_count | avg_monetary | avg_frequency |
|---|---|---|---|
| Platinum | ... | ... | ... |
| Gold | ... | ... | ... |
| Silver | ... | ... | ... |
| Bronze | ... | ... | ... |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Datetime + Timedelta  +  GroupBy Named Aggregation  +  pd.qcut (inverted + normal labels)  +  Composite Score Arithmetic  +  pd.cut (segment assignment)  +  pd.Categorical (ordered sort)  +  GroupBy + Named Aggregation (summary)
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `recency_days` = `(pd.Timestamp.today() - df["max_order_date"]).dt.days` — compute this on the aggregated result.
- For Recency, **lower days = better**, so use `labels=[4,3,2,1]` — the customer with the shortest gap gets score 4.
- `duplicates="drop"` in `pd.qcut()` handles cases where many customers have the same frequency value causing duplicate bin edges.
- `pd.cut(rfm_score, bins=[2, 3, 6, 9, 12], labels=["Bronze","Silver","Gold","Platinum"])` — adjust bins so 3 → Bronze, 4-6 → Silver, 7-9 → Gold, 10-12 → Platinum.
- Ordered sort: `order = pd.CategoricalDtype(["Platinum","Gold","Silver","Bronze"], ordered=True)` then `df["segment"] = df["segment"].astype(order)` before `sort_values("segment")`.

</details>

---

## ❓ Question 45

---

| | |
|---|---|
| **Question #** | 45 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The Finance team wants a **Year-over-Year revenue comparison per payment method**. The output is a wide-format table where each payment method is a row, years are columns, and each cell shows total revenue. For each payment method, also compute the **YoY growth %** from 2022→2023 and 2023→2024.

### 📝 Problem Statement

From `orders` (Delivered + non-null `amount_inr`):

1. Parse `order_date` as datetime; extract `order_year` = `.dt.year`
2. Filter to years 2022, 2023, 2024 only
3. Build a **pivot table**:
   - `index = payment_method`
   - `columns = order_year`
   - `values = amount_inr`
   - `aggfunc = "sum"`
4. Fill NaN with 0; round all values to 2 dp
5. Remove the column axis name
6. Compute:
   - `yoy_2022_to_2023_pct` = (2023 − 2022) / 2022 × 100, rounded to 2 dp
   - `yoy_2023_to_2024_pct` = (2024 − 2023) / 2023 × 100, rounded to 2 dp
   - Where denominator is 0, result should be `NaN` — handle with `.replace(0, pd.NA)` before dividing, or use `.where()`
7. Compute `total_revenue` = sum of all year columns per row
8. Sort by `total_revenue` descending

### ✅ Requirements

- The year columns (2022, 2023, 2024) will be **integers** after the pivot — access them as `df[2022]`, `df[2023]`, `df[2024]`
- Handle division by zero without `apply()` — use boolean masking or `.where(df[2022] != 0, (df[2023]-df[2022])/df[2022]*100, pd.NA)`

### 📊 Expected Output Format

| payment_method | 2022 | 2023 | 2024 | yoy_2022_to_2023_pct | yoy_2023_to_2024_pct | total_revenue |
|---|---|---|---|---|---|---|
| Credit Card | ... | ... | ... | +14.2 | −3.1 | ... |
| UPI | ... | ... | ... | +22.5 | +8.7 | ... |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Datetime + Year Extraction  +  Pivot Table (int year columns)  +  fillna + round  +  YoY % Arithmetic  +  Division-by-Zero Handling (vectorized)  +  Row-wise Sum  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- After `fillna(0)`, the zero values for some payment methods in some years will cause division-by-zero.
- Safest approach: `df["yoy_22_23"] = df[2023].sub(df[2022]).div(df[2022].replace(0, float("nan"))).mul(100).round(2)`
- `.replace(0, float("nan"))` converts zeros to NaN before division, making the result NaN instead of inf.
- Year columns will be integers: `df[2022]`, `df[2023]`, `df[2024]` — not strings.
- `df.columns.name = None` removes the "order_year" label from the column axis.
- `total_revenue = df[[2022, 2023, 2024]].sum(axis=1)` — be explicit about which columns to sum.

</details>

---

## ❓ Question 46

---

| | |
|---|---|
| **Question #** | 46 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The Product Analytics team wants a **Monthly Product Revenue Heatmap** — a wide-format table showing each product's total revenue for every month across the entire dataset. Each row is a product (cleaned name + category), each column is a month (`YYYY-MM`). Additionally, for each product, compute the **Month-over-Month (MoM) growth** for only its best month (the month with highest revenue vs. the previous month).

### 📝 Problem Statement

1. Filter `orders` to Delivered + non-null `amount_inr`; parse `order_date`; extract `order_month` period string
2. Clean `products.category` (strip + title); merge orders with products on `product_id` (inner join)
3. Group by `product_name`, `category`, `order_month`; compute `monthly_revenue` = sum of `amount_inr`
4. **Pivot**: `index = ["product_name","category"]`, `columns = order_month`, `values = monthly_revenue`
   - Use `pd.pivot_table()` with `aggfunc="sum"`
5. Fill NaN with 0; round all to 2 dp
6. Remove column axis name; reset index
7. Identify the **best month column** for each product (the column with the maximum value per row)
   - Use `df[month_cols].idxmax(axis=1)` → `best_month`
8. Get the **column index of `best_month`** within the sorted month columns, then look up the **previous month's revenue**
   - Use `.apply()` is forbidden — instead, use vectorized column indexing:
     `df.lookup()` is deprecated — use `df.to_numpy()` + integer position
     **Hint:** use `df[month_cols].stack().unstack()` and shift logic, OR build a helper Series using `idxmax` position
9. Compute `best_month_revenue` and `prev_month_revenue` for each product
10. Compute `best_month_mom_growth_pct` = (best − prev) / prev × 100, rounded to 2 dp
11. Add `best_month`, `best_month_revenue`, `prev_month_revenue`, `best_month_mom_growth_pct` columns to the result
12. Sort by `best_month_revenue` descending; show top 15 products

### ✅ Requirements

- No `apply()`, no loops for best_month MoM computation
- Use `idxmax(axis=1)` for best month identification
- Handle products whose best month is the first month (prev = NaN) gracefully

### 🧠 Concepts Tested

```
Boolean Filtering  +  String Cleaning  +  Inner Merge  +  GroupBy  +  pivot_table (multi-index)  +  fillna + round  +  idxmax(axis=1)  +  Vectorized Column Position Lookup  +  MoM Arithmetic  +  Sorting + head()
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- After building the pivot table, `month_cols` = all columns except `product_name` and `category`.
- `best_month = df[month_cols].idxmax(axis=1)` gives the column name (month string) of the max revenue per product.
- `best_month_revenue = df[month_cols].max(axis=1)`
- For `prev_month_revenue`: get the sorted list of month columns, find each product's best month's index position in that list, and look up the value at position-1.
  - `sorted_months = sorted(month_cols)` — months sort correctly as strings in "YYYY-MM" format.
  - `month_pos = pd.Series({m: i for i, m in enumerate(sorted_months)})` — a lookup dict.
  - `best_pos = best_month.map(month_pos)` — position of best month per product.
  - `prev_month_name = (best_pos - 1).map({i: m for i, m in enumerate(sorted_months)})` — previous month name.
  - Use `df[month_cols].to_numpy()` + `np.arange` and row/col indexing — but remember no NumPy! Instead, use `df.apply(lambda r: r[prev_month_name[r.name]], axis=1)` is forbidden too. Try using `df.stack()` and `.loc[]` with a MultiIndex for the vectorized lookup.

</details>

---

## ❓ Question 47

---

| | |
|---|---|
| **Question #** | 47 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The People Analytics team wants to detect **three types of attendance anomalies** across all 2024 attendance records. A single report should categorize employees into the anomaly they show — and employees may qualify for more than one:
- **Chronic Under-performer**: Every recorded month has `attendance_rate < 80%`
- **Sudden Drop**: Any month where `attendance_rate` drops by **20+ percentage points** vs. the prior month
- **Perfect Attendance**: Every recorded month has `attendance_rate == 100%`

### 📝 Problem Statement

1. From `attendance`: parse `month`; filter to year 2024; drop null `present_days`
2. Compute `attendance_rate` = (`present_days` / `working_days`) × 100 per row
3. Sort by `emp_id` ASC, `month` ASC
4. For each `emp_id` compute:
   - `month_count` = number of recorded months — use `groupby + transform("count")`
   - `min_rate` = minimum attendance rate — `transform("min")`
   - `max_rate` = maximum attendance rate — `transform("max")`
   - `rate_diff` = difference in `attendance_rate` from the prior month — `groupby + diff(1)`
5. Identify flags at the **employee level** (one row per emp_id):
   a. `is_chronic_underperformer` = True if ALL months have `attendance_rate < 80` → `max_rate < 80`
   b. `has_sudden_drop` = True if any month has `rate_diff <= -20`
   c. `is_perfect_attendance` = True if ALL months have `attendance_rate == 100` → `min_rate == 100`
6. Collapse to **one row per emp_id**:
   - Group by `emp_id`, aggregate: `month_count` (first), `min_rate` (first), `max_rate` (first), `is_chronic_underperformer` (first), `is_perfect_attendance` (first), `has_sudden_drop` = any True in `rate_diff <= -20`
7. Keep only employees with **at least one anomaly flag = True**
8. Merge with employees (inner join) to get `employee_name` and `dept_id`
9. Sort by `emp_id`; reset index

### ✅ Requirements

- `has_sudden_drop` requires a **per-employee boolean aggregation** — compute `rate_diff <= -20` first, then group by `emp_id` and use `any()`
- Use `transform` for all employee-level stats before collapsing
- No loops, no `apply()`

### 📊 Expected Output Format

| emp_id | employee_name | dept_id | month_count | min_rate | max_rate | is_chronic_underperformer | has_sudden_drop | is_perfect_attendance |
|---|---|---|---|---|---|---|---|---|
| E... | ... | D03 | 6 | 45.45 | 77.27 | True | False | False |
| E... | ... | D05 | 6 | 100.0 | 100.0 | False | False | True |
| ... | | | | | | | | |

### 🧠 Concepts Tested

```
Datetime + Year Filter  +  Computed Column  +  Sorting  +  GroupBy Transform (count, min, max)  +  GroupBy diff()  +  Row-level Boolean Flags  +  GroupBy Aggregation (any, first)  +  Multi-flag Filter  +  Inner Merge  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Sort by `["emp_id","month"]` **before** computing `diff(1)` — otherwise the diff will be in the wrong order.
- `groupby("emp_id")["attendance_rate"].diff(1)` computes the row-by-row difference within each employee group.
- For `has_sudden_drop`: create a boolean column `sudden_drop_flag = rate_diff <= -20`, then `groupby("emp_id")["sudden_drop_flag"].any()` — this collapses to one True/False per employee.
- For `is_chronic_underperformer` and `is_perfect_attendance`: these can be derived from `max_rate` and `min_rate` respectively — no extra groupby needed.
- After collapsing to one row per emp_id (using `groupby(...).agg({...})`), filter where any of the three flags is True: `(chronic) | (sudden) | (perfect)`.

</details>

---

## ❓ Question 48

---

| | |
|---|---|
| **Question #** | 48 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The Executive team wants a **360° Department Summary** — a single row per department that combines HR data (headcount, avg salary, budget utilization), operational data (attendance rate), and financial data (total revenue from the city's customers). This is the kind of cross-domain report that requires joining multiple datasets into one coherent pipeline.

### 📝 Problem Statement

**HR Metrics (from employees + departments):**
1. Active employees (dedup by emp_id, non-null salary); merge with departments
2. GroupBy `department_name`: `headcount` (count), `total_salary_cost` (sum), `avg_salary` (mean, rounded 2dp)
3. Compute `budget_utilization_pct` = `total_salary_cost / budget_inr * 100` (rounded 2dp)

**Attendance Metrics (from attendance + employees):**
4. Filter attendance to all of 2024; drop null `present_days`; compute `attendance_rate` per row
5. Merge with active employees (inner join) then with departments (inner join)
6. GroupBy `department_name`: `avg_attendance_rate` (mean of `attendance_rate`, rounded 2dp)

**Order Metrics (from orders + customers):**
7. Filter orders to Delivered + non-null `amount_inr`; dedup customers; merge orders with customers
8. GroupBy `city` (customers' city): `city_total_revenue` = sum of `amount_inr`
9. Merge this city revenue with the HR summary via the **dominant city per department** — compute the most common `city` among Active employees per `department_name` using `groupby + value_counts + idxmax`

**Combine:**
10. Merge HR summary + Attendance summary on `department_name` (inner join)
11. Merge with city revenue on the dominant city (left join)
12. Final columns: `department_name`, `headcount`, `avg_salary`, `budget_utilization_pct`, `avg_attendance_rate`, `dominant_city`, `city_total_revenue`
13. Sort by `budget_utilization_pct` descending

### ✅ Requirements

- Three independent pipelines then merged — structure your code clearly
- Dominant city: `groupby(["department_name","city"]).size().groupby(level=0).idxmax()` pattern
- No loops, no `apply()`

### 🧠 Concepts Tested

```
Three Independent Pipelines  +  Multiple Merges (4+ total)  +  Multiple GroupBys  +  Dominant Value Extraction (groupby + idxmax)  +  Multi-level Index Navigation  +  Left Merge (city revenue)  +  Final Column Selection  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- Build three separate DataFrames first: `hr_summary`, `att_summary`, `city_revenue` — then merge.
- For the dominant city per department:
  `dept_city = merged_emp[["department_name","city"]].groupby(["department_name","city"]).size()`
  `dominant_city = dept_city.groupby(level=0).idxmax()` — this returns a Series of (dept, city) tuples.
  `dominant_city = dominant_city.apply(lambda x: x[1])` — wait, no `apply()`. Instead:
  `dominant_city = dept_city.reset_index(name="count").sort_values("count",ascending=False).drop_duplicates("department_name").set_index("department_name")["city"]`
- The city revenue merge uses a left join so departments without any customer orders in their city still appear (with NaN revenue).
- `fillna(0)` on `city_total_revenue` after the left join for clean output.

</details>

---

## ❓ Question 49

---

| | |
|---|---|
| **Question #** | 49 of 50 |
| **Difficulty** | 🔥 Hard |
| **Interview Level** | Senior / Lead |

### 🏢 Business Scenario

The Revenue Operations team wants a **Payment Method Efficiency Report** — for each payment method, they want to understand: what proportion of orders **successfully deliver** vs get cancelled/returned, and how does the average order value differ by status. The report must then compute a **delivery efficiency score** per payment method and rank them.

### 📝 Problem Statement

From `orders` (all statuses; non-null `amount_inr` only):

1. Build a pivot table:
   - `index = payment_method`
   - `columns = order_status`
   - `values = amount_inr`
   - `aggfunc = ["count","mean"]` — two aggregation functions
   - This produces a MultiIndex column structure
2. Fill NaN with 0; round `mean` columns to 2 dp
3. Flatten the MultiIndex columns to: `<status>_count` and `<status>_mean` patterns
4. Compute:
   - `total_orders` = sum of all `_count` columns
   - `delivered_rate` = `Delivered_count / total_orders * 100`, rounded to 2 dp
   - `cancelled_returned_rate` = (`Cancelled_count` + `Returned_count`) / `total_orders * 100`, rounded to 2 dp
   - `avg_delivered_value` = `Delivered_mean` (already computed in pivot)
   - `efficiency_score` = `delivered_rate` − `cancelled_returned_rate` (higher = better)
5. Add `efficiency_rank` = dense rank of `efficiency_score` descending (as int)
6. Select: `payment_method`, `total_orders`, `delivered_rate`, `cancelled_returned_rate`, `avg_delivered_value`, `efficiency_score`, `efficiency_rank`
7. Sort by `efficiency_rank` ascending

### ✅ Requirements

- Use `aggfunc=["count","mean"]` in `pd.pivot_table()` — produces MultiIndex columns
- Flatten MultiIndex: `["_".join(reversed(c)).strip() for c in df.columns]`
- Handle missing status columns (e.g., if "Returned" has no records for a payment method) via `fillna(0)`

### 📊 Expected Output Format

| payment_method | total_orders | delivered_rate | cancelled_returned_rate | avg_delivered_value | efficiency_score | efficiency_rank |
|---|---|---|---|---|---|---|
| Credit Card | ... | 45.2 | 18.3 | ... | 26.9 | 1 |
| UPI | ... | 42.1 | 21.5 | ... | 20.6 | 2 |
| ... | | | | | | |

### 🧠 Concepts Tested

```
Boolean Filtering  +  Pivot Table (aggfunc list → MultiIndex columns)  +  MultiIndex Column Flattening  +  fillna + round  +  Derived Metrics (rate, score)  +  rank()  +  Column Selection  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- `pd.pivot_table(..., aggfunc=["count","mean"])` creates a **two-level column** MultiIndex: top level = `count`/`mean`, bottom level = order_status values.
- Flatten with: `df.columns = [f"{status}_{agg}" for agg, status in df.columns]` — note the order: `df.columns` is `(aggfunc, status)` tuples.
- After flattening, you'll have columns like `Delivered_count`, `Delivered_mean`, `Cancelled_count`, etc.
- `total_orders = df[[c for c in df.columns if c.endswith("_count")]].sum(axis=1)` — sum only the count columns.
- If "Returned" or "Cancelled" columns don't exist for some pivot configurations, `df.get("Cancelled_count", 0)` or `reindex` them first.

</details>

---

## ❓ Question 50 — The Grand Finale 🏆

---

| | |
|---|---|
| **Question #** | 50 of 50 |
| **Difficulty** | 🔥🔥 Hardest |
| **Interview Level** | Staff / Principal |

### 🏢 Business Scenario

The CEO wants a single **Top Employee Per Department** report based on a multi-factor performance score. The score combines three normalized metrics:
- **Salary score** (40%): Employee's salary as a percentile within their department
- **Attendance score** (40%): Employee's avg H1 2024 attendance rate normalized to 0–100
- **Transaction score** (20%): Employee's total Successful H1 2024 transaction amount, ranked as a percentile across all employees

Find the **single highest-scoring employee per department** and produce a leaderboard enriched with department names.

### 📝 Problem Statement

**Step 1 — Salary Percentile:**
1. `employees` — Active, deduplicated, non-null salary
2. `salary_pct` = `groupby("dept_id")["salary_inr"].rank(pct=True) * 100`

**Step 2 — Attendance Score:**
3. Filter `attendance` to H1 2024 (year=2024, month≤6); drop null `present_days`
4. Compute `attendance_rate` per row; group by `emp_id`, compute `avg_att_rate` = mean (rounded 2dp)
5. `attendance_score` = `avg_att_rate` (already 0–100 scale — no transformation needed)

**Step 3 — Transaction Percentile:**
6. Filter `transactions` to `txn_status=="Success"`, non-null `amount_inr`, H1 2024
7. Group by `emp_id`, compute `total_txn_amount` = sum of `amount_inr`
8. `txn_pct` = `total_txn_amount.rank(pct=True) * 100` (global percentile across all employees)

**Step 4 — Merge & Score:**
9. Start from Active employees (from Step 1); left join attendance summary; left join transaction summary
10. Fill missing `avg_att_rate` with 0; fill missing `total_txn_amount` with 0; fill missing `txn_pct` with 0
11. Compute `composite_score` = (`salary_pct` × 0.40) + (`attendance_score` × 0.40) + (`txn_pct` × 0.20), rounded to 2 dp

**Step 5 — Top Employee Per Dept:**
12. Within each `dept_id`, find the employee with the **highest `composite_score`** — use `groupby("dept_id")["composite_score"].transform("max")` and filter where `composite_score == dept_max`
13. Merge with `departments` (inner join) to get `department_name`
14. Select: `department_name`, `emp_id`, `employee_name`, `salary_inr`, `salary_pct`, `avg_att_rate`, `txn_pct`, `composite_score`
15. Round `salary_pct` and `txn_pct` to 2 dp
16. Sort by `composite_score` descending
17. Reset index

### ✅ Requirements

- Three independent pipelines, then left-joined onto employees
- `txn_pct` is computed on the aggregated transaction DataFrame, then brought in via merge
- `transform("max")` for top-per-group selection — not `nlargest()` with `groupby`
- If two employees tie for the top score in a dept, both should appear

### 📊 Expected Output Format

| department_name | emp_id | employee_name | salary_inr | salary_pct | avg_att_rate | txn_pct | composite_score |
|---|---|---|---|---|---|---|---|
| Data Science | E... | ... | 112000 | 100.0 | 93.18 | 88.2 | 96.44 |
| Engineering | E... | ... | 98000 | 87.5 | 91.67 | 75.0 | 87.5 |
| ... | | | | | | | |

### 🧠 Concepts Tested

```
Three Independent Pipelines  +  groupby + rank(pct=True) × 2  +  Attendance Pipeline  +  Transaction Pipeline  +  Three Sequential Left Merges  +  fillna × 3  +  Weighted Composite Score  +  GroupBy + Transform(max) for Top-1  +  Inner Merge (departments)  +  round() × multiple  +  Sorting
```

<details>
<summary>💡 Hint — Click to expand (try on your own first!)</summary>

<br>

- **Plan first**: sketch the three pipelines on paper before coding. Each produces a small DataFrame keyed by `emp_id`.
- **salary_pct**: computed directly on the employee DataFrame using `groupby("dept_id")["salary_inr"].rank(pct=True)`.
- **txn_pct**: computed on the aggregated transaction summary (one row per emp_id) using `total_txn_amount.rank(pct=True)`. The rank is done globally (all employees who had transactions), not per dept.
- Left joins ensure employees with no attendance or no transactions still appear — fill their scores with 0.
- `composite_score = (salary_pct * 0.40) + (avg_att_rate * 0.40) + (txn_pct * 0.20)` — all three are already on a 0–100 scale.
- For top-per-dept: `df["dept_max"] = df.groupby("dept_id")["composite_score"].transform("max")` then filter `df[df["composite_score"] == df["dept_max"]]`.
- Congratulations — if you solved this, you're ready for production Pandas interviews! 🏆

</details>

---
---

<div style="background: linear-gradient(135deg, #0f3460 0%, #16213e 50%, #0f3460 100%); padding: 50px 40px; border-radius: 16px; text-align: center; font-family: 'Segoe UI', Arial, sans-serif; border: 2px solid #f4d03f; box-shadow: 0 0 40px rgba(244,208,63,0.15);">

<div style="font-size: 3.5em; margin-bottom: 12px;">🏆</div>
<h1 style="color: #f4d03f; margin: 0 0 8px 0; font-size: 2em;">Congratulations!</h1>
<h3 style="color: #a8dadc; margin: 0 0 20px 0; font-weight: 400;">You have completed all 50 questions in Notebook 1</h3>

<p style="color: #f1faee; font-size: 1.05em; max-width: 600px; margin: 0 auto 24px auto; line-height: 1.7;">
You have practiced across the full spectrum — from foundational filtering and merging to production-grade multi-pipeline analytics. Each question forced you to think in Pandas: vectorized, composable, and clean.
</p>

</div>

---

## 🎯 Key Takeaways from Notebook 1

| Concept | Where You Used It |
|---|---|
| **String cleaning** (`str.strip`, `str.title`) | Q2, Q12, Q16, Q18, Q26, Q35, Q42 |
| **Datetime parsing & .dt accessor** | Q4, Q14, Q22, Q23, Q29, Q31, Q41 |
| **GroupBy + Named Aggregation** | Q5, Q9, Q12, Q16, Q19, Q32, Q33 |
| **Merge (left, inner, self)** | Q3, Q13, Q16, Q19, Q26, Q37, Q42, Q48 |
| **transform()** | Q15, Q25, Q27, Q40, Q43, Q47, Q50 |
| **pivot_table + unstack** | Q11, Q17, Q21, Q25, Q30, Q45, Q49 |
| **rank() — dense, pct** | Q20, Q26, Q34, Q35, Q43, Q49, Q50 |
| **cumsum / shift** | Q15, Q22, Q31, Q32 |
| **pd.cut / pd.qcut** | Q21, Q29, Q44 |
| **isin + negation (~)** | Q23, Q28, Q36 |
| **rolling().mean()** | Q31 |
| **Multi-pipeline composition** | Q40, Q48, Q50 |

---

## 💡 Pandas Interview Rules You Should Never Forget

```
1. Always filter FIRST — shrink data before merging or grouping
2. Clean strings BEFORE merging — dirty keys break joins silently
3. fillna() BEFORE groupby sum — NaN propagates and ruins totals
4. Sort BEFORE shift() or diff() — order matters for time-series ops
5. transform() keeps shape; agg() reduces shape — know which you need
6. rank(pct=True) gives percentiles; rank(method="dense") handles ties
7. unstack() reshapes from long to wide; stack() goes wide to long
8. pd.cut() = fixed bins; pd.qcut() = equal-frequency bins
9. isin() + ~ is your set-difference tool — never use Python set()
10. Build 3 clean pipelines and merge — never try to do everything in one query
```

---
---

<div style="background: linear-gradient(135deg, #1b4332 0%, #2d6a4f 100%); padding: 40px 36px; border-radius: 14px; font-family: 'Segoe UI', Arial, sans-serif; border: 1px solid #52b788;">

<h2 style="color: #d8f3dc; margin: 0 0 20px 0;">🚀 What's Next: Notebook 2</h2>

<p style="color: #b7e4c7; font-size: 0.97em; margin: 0 0 16px 0;">
Notebook 2 uses exclusively <strong>Seaborn's built-in datasets</strong> — datasets like <code>titanic</code>, <code>tips</code>, <code>flights</code>, <code>diamonds</code>, and <code>penguins</code>. These are clean, well-known, and used across the ML/DS community — perfect for interview practice.
</p>

<table style="color: #d8f3dc; width: 100%; border-collapse: collapse; margin-bottom: 16px;">
<tr style="border-bottom: 1px solid #52b788;">
<th style="padding: 10px; text-align: left; color: #95d5b2;">Notebook 2 Dataset</th>
<th style="padding: 10px; text-align: left; color: #95d5b2;">Focus</th>
</tr>
<tr style="border-bottom: 1px solid #40916c;">
<td style="padding: 8px;"><code>sns.load_dataset("titanic")</code></td>
<td style="padding: 8px;">Survival analysis, missing value handling, crosstabs</td>
</tr>
<tr style="border-bottom: 1px solid #40916c;">
<td style="padding: 8px;"><code>sns.load_dataset("tips")</code></td>
<td style="padding: 8px;">Pivot analysis, tip rate, group comparisons</td>
</tr>
<tr style="border-bottom: 1px solid #40916c;">
<td style="padding: 8px;"><code>sns.load_dataset("flights")</code></td>
<td style="padding: 8px;">Time-series reshaping, rolling, YoY trends</td>
</tr>
<tr style="border-bottom: 1px solid #40916c;">
<td style="padding: 8px;"><code>sns.load_dataset("diamonds")</code></td>
<td style="padding: 8px;">Price analysis, cut/color/clarity breakdowns, rank</td>
</tr>
<tr>
<td style="padding: 8px;"><code>sns.load_dataset("penguins")</code></td>
<td style="padding: 8px;">Missing data, group stats, species comparisons</td>
</tr>
</table>

<p style="color: #95d5b2; font-size: 0.9em; margin: 0;">📌 Notebook 2 will continue the difficulty curve — 50 more questions, exclusively Pandas, no other libraries.</p>

</div>

---

## 🏁 Final Progress Tracker

| Batch | Questions | Difficulty | Status |
|---|---|---|---|
| Batch 1 | 1 – 10 | 🟢 Easy → 🟡 Easy-Medium | ✅ Completed |
| Batch 2 | 11 – 20 | 🟠 Medium | ✅ Completed |
| Batch 3 | 21 – 30 | 🔴 Medium-Hard | ✅ Completed |
| Batch 4 | 31 – 40 | 🔥 Hard | ✅ Completed |
| Batch 5 | 41 – 50 | 🔥 Hard (Final) | ✅ Completed |

---

> *"An expert is someone who has made all the mistakes that can be made in a very narrow field."*
> — Niels Bohr

---
---